// Code generated by Kitex v0.16.1. DO NOT EDIT.

package assetservice

import (
	"context"
	"errors"
	asset "github.com/castlexu/micro-service/services/edge-api/kitex_gen/asset"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newAssetServiceHealthArgs,
		newAssetServiceHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateAssetType": kitex.NewMethodInfo(
		createAssetTypeHandler,
		newAssetServiceCreateAssetTypeArgs,
		newAssetServiceCreateAssetTypeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAssetType": kitex.NewMethodInfo(
		updateAssetTypeHandler,
		newAssetServiceUpdateAssetTypeArgs,
		newAssetServiceUpdateAssetTypeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAssetType": kitex.NewMethodInfo(
		getAssetTypeHandler,
		newAssetServiceGetAssetTypeArgs,
		newAssetServiceGetAssetTypeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAssetTypes": kitex.NewMethodInfo(
		listAssetTypesHandler,
		newAssetServiceListAssetTypesArgs,
		newAssetServiceListAssetTypesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAssetType": kitex.NewMethodInfo(
		deleteAssetTypeHandler,
		newAssetServiceDeleteAssetTypeArgs,
		newAssetServiceDeleteAssetTypeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateAssetCategory": kitex.NewMethodInfo(
		createAssetCategoryHandler,
		newAssetServiceCreateAssetCategoryArgs,
		newAssetServiceCreateAssetCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAssetCategory": kitex.NewMethodInfo(
		updateAssetCategoryHandler,
		newAssetServiceUpdateAssetCategoryArgs,
		newAssetServiceUpdateAssetCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAssetCategories": kitex.NewMethodInfo(
		listAssetCategoriesHandler,
		newAssetServiceListAssetCategoriesArgs,
		newAssetServiceListAssetCategoriesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAssetCategory": kitex.NewMethodInfo(
		deleteAssetCategoryHandler,
		newAssetServiceDeleteAssetCategoryArgs,
		newAssetServiceDeleteAssetCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateAsset": kitex.NewMethodInfo(
		createAssetHandler,
		newAssetServiceCreateAssetArgs,
		newAssetServiceCreateAssetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAsset": kitex.NewMethodInfo(
		updateAssetHandler,
		newAssetServiceUpdateAssetArgs,
		newAssetServiceUpdateAssetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAsset": kitex.NewMethodInfo(
		getAssetHandler,
		newAssetServiceGetAssetArgs,
		newAssetServiceGetAssetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAssets": kitex.NewMethodInfo(
		listAssetsHandler,
		newAssetServiceListAssetsArgs,
		newAssetServiceListAssetsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetAssetLibraryState": kitex.NewMethodInfo(
		setAssetLibraryStateHandler,
		newAssetServiceSetAssetLibraryStateArgs,
		newAssetServiceSetAssetLibraryStateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAsset": kitex.NewMethodInfo(
		deleteAssetHandler,
		newAssetServiceDeleteAssetArgs,
		newAssetServiceDeleteAssetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateAssetVersion": kitex.NewMethodInfo(
		createAssetVersionHandler,
		newAssetServiceCreateAssetVersionArgs,
		newAssetServiceCreateAssetVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CopyAssetVersion": kitex.NewMethodInfo(
		copyAssetVersionHandler,
		newAssetServiceCopyAssetVersionArgs,
		newAssetServiceCopyAssetVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAssetVersion": kitex.NewMethodInfo(
		getAssetVersionHandler,
		newAssetServiceGetAssetVersionArgs,
		newAssetServiceGetAssetVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCurrentAssetVersion": kitex.NewMethodInfo(
		getCurrentAssetVersionHandler,
		newAssetServiceGetCurrentAssetVersionArgs,
		newAssetServiceGetCurrentAssetVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAssetVersions": kitex.NewMethodInfo(
		listAssetVersionsHandler,
		newAssetServiceListAssetVersionsArgs,
		newAssetServiceListAssetVersionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetCurrentAssetVersion": kitex.NewMethodInfo(
		setCurrentAssetVersionHandler,
		newAssetServiceSetCurrentAssetVersionArgs,
		newAssetServiceSetCurrentAssetVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	assetServiceServiceInfo                = NewServiceInfo()
	assetServiceServiceInfoForClient       = NewServiceInfoForClient()
	assetServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return assetServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return assetServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return assetServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AssetService"
	handlerType := (*asset.AssetService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "asset",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceHealthArgs)
	realResult := result.(*asset.AssetServiceHealthResult)
	success, err := handler.(asset.AssetService).Health(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceHealthArgs() interface{} {
	return asset.NewAssetServiceHealthArgs()
}

func newAssetServiceHealthResult() interface{} {
	return asset.NewAssetServiceHealthResult()
}

func createAssetTypeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceCreateAssetTypeArgs)
	realResult := result.(*asset.AssetServiceCreateAssetTypeResult)
	success, err := handler.(asset.AssetService).CreateAssetType(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceCreateAssetTypeArgs() interface{} {
	return asset.NewAssetServiceCreateAssetTypeArgs()
}

func newAssetServiceCreateAssetTypeResult() interface{} {
	return asset.NewAssetServiceCreateAssetTypeResult()
}

func updateAssetTypeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceUpdateAssetTypeArgs)
	realResult := result.(*asset.AssetServiceUpdateAssetTypeResult)
	success, err := handler.(asset.AssetService).UpdateAssetType(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceUpdateAssetTypeArgs() interface{} {
	return asset.NewAssetServiceUpdateAssetTypeArgs()
}

func newAssetServiceUpdateAssetTypeResult() interface{} {
	return asset.NewAssetServiceUpdateAssetTypeResult()
}

func getAssetTypeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceGetAssetTypeArgs)
	realResult := result.(*asset.AssetServiceGetAssetTypeResult)
	success, err := handler.(asset.AssetService).GetAssetType(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceGetAssetTypeArgs() interface{} {
	return asset.NewAssetServiceGetAssetTypeArgs()
}

func newAssetServiceGetAssetTypeResult() interface{} {
	return asset.NewAssetServiceGetAssetTypeResult()
}

func listAssetTypesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceListAssetTypesArgs)
	realResult := result.(*asset.AssetServiceListAssetTypesResult)
	success, err := handler.(asset.AssetService).ListAssetTypes(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceListAssetTypesArgs() interface{} {
	return asset.NewAssetServiceListAssetTypesArgs()
}

func newAssetServiceListAssetTypesResult() interface{} {
	return asset.NewAssetServiceListAssetTypesResult()
}

func deleteAssetTypeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceDeleteAssetTypeArgs)
	realResult := result.(*asset.AssetServiceDeleteAssetTypeResult)
	success, err := handler.(asset.AssetService).DeleteAssetType(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceDeleteAssetTypeArgs() interface{} {
	return asset.NewAssetServiceDeleteAssetTypeArgs()
}

func newAssetServiceDeleteAssetTypeResult() interface{} {
	return asset.NewAssetServiceDeleteAssetTypeResult()
}

func createAssetCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceCreateAssetCategoryArgs)
	realResult := result.(*asset.AssetServiceCreateAssetCategoryResult)
	success, err := handler.(asset.AssetService).CreateAssetCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceCreateAssetCategoryArgs() interface{} {
	return asset.NewAssetServiceCreateAssetCategoryArgs()
}

func newAssetServiceCreateAssetCategoryResult() interface{} {
	return asset.NewAssetServiceCreateAssetCategoryResult()
}

func updateAssetCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceUpdateAssetCategoryArgs)
	realResult := result.(*asset.AssetServiceUpdateAssetCategoryResult)
	success, err := handler.(asset.AssetService).UpdateAssetCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceUpdateAssetCategoryArgs() interface{} {
	return asset.NewAssetServiceUpdateAssetCategoryArgs()
}

func newAssetServiceUpdateAssetCategoryResult() interface{} {
	return asset.NewAssetServiceUpdateAssetCategoryResult()
}

func listAssetCategoriesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceListAssetCategoriesArgs)
	realResult := result.(*asset.AssetServiceListAssetCategoriesResult)
	success, err := handler.(asset.AssetService).ListAssetCategories(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceListAssetCategoriesArgs() interface{} {
	return asset.NewAssetServiceListAssetCategoriesArgs()
}

func newAssetServiceListAssetCategoriesResult() interface{} {
	return asset.NewAssetServiceListAssetCategoriesResult()
}

func deleteAssetCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceDeleteAssetCategoryArgs)
	realResult := result.(*asset.AssetServiceDeleteAssetCategoryResult)
	success, err := handler.(asset.AssetService).DeleteAssetCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceDeleteAssetCategoryArgs() interface{} {
	return asset.NewAssetServiceDeleteAssetCategoryArgs()
}

func newAssetServiceDeleteAssetCategoryResult() interface{} {
	return asset.NewAssetServiceDeleteAssetCategoryResult()
}

func createAssetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceCreateAssetArgs)
	realResult := result.(*asset.AssetServiceCreateAssetResult)
	success, err := handler.(asset.AssetService).CreateAsset(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceCreateAssetArgs() interface{} {
	return asset.NewAssetServiceCreateAssetArgs()
}

func newAssetServiceCreateAssetResult() interface{} {
	return asset.NewAssetServiceCreateAssetResult()
}

func updateAssetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceUpdateAssetArgs)
	realResult := result.(*asset.AssetServiceUpdateAssetResult)
	success, err := handler.(asset.AssetService).UpdateAsset(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceUpdateAssetArgs() interface{} {
	return asset.NewAssetServiceUpdateAssetArgs()
}

func newAssetServiceUpdateAssetResult() interface{} {
	return asset.NewAssetServiceUpdateAssetResult()
}

func getAssetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceGetAssetArgs)
	realResult := result.(*asset.AssetServiceGetAssetResult)
	success, err := handler.(asset.AssetService).GetAsset(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceGetAssetArgs() interface{} {
	return asset.NewAssetServiceGetAssetArgs()
}

func newAssetServiceGetAssetResult() interface{} {
	return asset.NewAssetServiceGetAssetResult()
}

func listAssetsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceListAssetsArgs)
	realResult := result.(*asset.AssetServiceListAssetsResult)
	success, err := handler.(asset.AssetService).ListAssets(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceListAssetsArgs() interface{} {
	return asset.NewAssetServiceListAssetsArgs()
}

func newAssetServiceListAssetsResult() interface{} {
	return asset.NewAssetServiceListAssetsResult()
}

func setAssetLibraryStateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceSetAssetLibraryStateArgs)
	realResult := result.(*asset.AssetServiceSetAssetLibraryStateResult)
	success, err := handler.(asset.AssetService).SetAssetLibraryState(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceSetAssetLibraryStateArgs() interface{} {
	return asset.NewAssetServiceSetAssetLibraryStateArgs()
}

func newAssetServiceSetAssetLibraryStateResult() interface{} {
	return asset.NewAssetServiceSetAssetLibraryStateResult()
}

func deleteAssetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceDeleteAssetArgs)
	realResult := result.(*asset.AssetServiceDeleteAssetResult)
	success, err := handler.(asset.AssetService).DeleteAsset(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceDeleteAssetArgs() interface{} {
	return asset.NewAssetServiceDeleteAssetArgs()
}

func newAssetServiceDeleteAssetResult() interface{} {
	return asset.NewAssetServiceDeleteAssetResult()
}

func createAssetVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceCreateAssetVersionArgs)
	realResult := result.(*asset.AssetServiceCreateAssetVersionResult)
	success, err := handler.(asset.AssetService).CreateAssetVersion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceCreateAssetVersionArgs() interface{} {
	return asset.NewAssetServiceCreateAssetVersionArgs()
}

func newAssetServiceCreateAssetVersionResult() interface{} {
	return asset.NewAssetServiceCreateAssetVersionResult()
}

func copyAssetVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceCopyAssetVersionArgs)
	realResult := result.(*asset.AssetServiceCopyAssetVersionResult)
	success, err := handler.(asset.AssetService).CopyAssetVersion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceCopyAssetVersionArgs() interface{} {
	return asset.NewAssetServiceCopyAssetVersionArgs()
}

func newAssetServiceCopyAssetVersionResult() interface{} {
	return asset.NewAssetServiceCopyAssetVersionResult()
}

func getAssetVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceGetAssetVersionArgs)
	realResult := result.(*asset.AssetServiceGetAssetVersionResult)
	success, err := handler.(asset.AssetService).GetAssetVersion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceGetAssetVersionArgs() interface{} {
	return asset.NewAssetServiceGetAssetVersionArgs()
}

func newAssetServiceGetAssetVersionResult() interface{} {
	return asset.NewAssetServiceGetAssetVersionResult()
}

func getCurrentAssetVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceGetCurrentAssetVersionArgs)
	realResult := result.(*asset.AssetServiceGetCurrentAssetVersionResult)
	success, err := handler.(asset.AssetService).GetCurrentAssetVersion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceGetCurrentAssetVersionArgs() interface{} {
	return asset.NewAssetServiceGetCurrentAssetVersionArgs()
}

func newAssetServiceGetCurrentAssetVersionResult() interface{} {
	return asset.NewAssetServiceGetCurrentAssetVersionResult()
}

func listAssetVersionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceListAssetVersionsArgs)
	realResult := result.(*asset.AssetServiceListAssetVersionsResult)
	success, err := handler.(asset.AssetService).ListAssetVersions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceListAssetVersionsArgs() interface{} {
	return asset.NewAssetServiceListAssetVersionsArgs()
}

func newAssetServiceListAssetVersionsResult() interface{} {
	return asset.NewAssetServiceListAssetVersionsResult()
}

func setCurrentAssetVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*asset.AssetServiceSetCurrentAssetVersionArgs)
	realResult := result.(*asset.AssetServiceSetCurrentAssetVersionResult)
	success, err := handler.(asset.AssetService).SetCurrentAssetVersion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAssetServiceSetCurrentAssetVersionArgs() interface{} {
	return asset.NewAssetServiceSetCurrentAssetVersionArgs()
}

func newAssetServiceSetCurrentAssetVersionResult() interface{} {
	return asset.NewAssetServiceSetCurrentAssetVersionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Health(ctx context.Context, req *asset.HealthReq) (r *asset.HealthResp, err error) {
	var _args asset.AssetServiceHealthArgs
	_args.Req = req
	var _result asset.AssetServiceHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAssetType(ctx context.Context, req *asset.CreateAssetTypeReq) (r *asset.CreateAssetTypeResp, err error) {
	var _args asset.AssetServiceCreateAssetTypeArgs
	_args.Req = req
	var _result asset.AssetServiceCreateAssetTypeResult
	if err = p.c.Call(ctx, "CreateAssetType", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAssetType(ctx context.Context, req *asset.UpdateAssetTypeReq) (r *asset.UpdateAssetTypeResp, err error) {
	var _args asset.AssetServiceUpdateAssetTypeArgs
	_args.Req = req
	var _result asset.AssetServiceUpdateAssetTypeResult
	if err = p.c.Call(ctx, "UpdateAssetType", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAssetType(ctx context.Context, req *asset.GetAssetTypeReq) (r *asset.GetAssetTypeResp, err error) {
	var _args asset.AssetServiceGetAssetTypeArgs
	_args.Req = req
	var _result asset.AssetServiceGetAssetTypeResult
	if err = p.c.Call(ctx, "GetAssetType", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAssetTypes(ctx context.Context, req *asset.ListAssetTypesReq) (r *asset.ListAssetTypesResp, err error) {
	var _args asset.AssetServiceListAssetTypesArgs
	_args.Req = req
	var _result asset.AssetServiceListAssetTypesResult
	if err = p.c.Call(ctx, "ListAssetTypes", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAssetType(ctx context.Context, req *asset.DeleteAssetTypeReq) (r *asset.DeleteAssetTypeResp, err error) {
	var _args asset.AssetServiceDeleteAssetTypeArgs
	_args.Req = req
	var _result asset.AssetServiceDeleteAssetTypeResult
	if err = p.c.Call(ctx, "DeleteAssetType", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAssetCategory(ctx context.Context, req *asset.CreateAssetCategoryReq) (r *asset.CreateAssetCategoryResp, err error) {
	var _args asset.AssetServiceCreateAssetCategoryArgs
	_args.Req = req
	var _result asset.AssetServiceCreateAssetCategoryResult
	if err = p.c.Call(ctx, "CreateAssetCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAssetCategory(ctx context.Context, req *asset.UpdateAssetCategoryReq) (r *asset.UpdateAssetCategoryResp, err error) {
	var _args asset.AssetServiceUpdateAssetCategoryArgs
	_args.Req = req
	var _result asset.AssetServiceUpdateAssetCategoryResult
	if err = p.c.Call(ctx, "UpdateAssetCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAssetCategories(ctx context.Context, req *asset.ListAssetCategoriesReq) (r *asset.ListAssetCategoriesResp, err error) {
	var _args asset.AssetServiceListAssetCategoriesArgs
	_args.Req = req
	var _result asset.AssetServiceListAssetCategoriesResult
	if err = p.c.Call(ctx, "ListAssetCategories", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAssetCategory(ctx context.Context, req *asset.DeleteAssetCategoryReq) (r *asset.DeleteAssetCategoryResp, err error) {
	var _args asset.AssetServiceDeleteAssetCategoryArgs
	_args.Req = req
	var _result asset.AssetServiceDeleteAssetCategoryResult
	if err = p.c.Call(ctx, "DeleteAssetCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAsset(ctx context.Context, req *asset.CreateAssetReq) (r *asset.CreateAssetResp, err error) {
	var _args asset.AssetServiceCreateAssetArgs
	_args.Req = req
	var _result asset.AssetServiceCreateAssetResult
	if err = p.c.Call(ctx, "CreateAsset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAsset(ctx context.Context, req *asset.UpdateAssetReq) (r *asset.UpdateAssetResp, err error) {
	var _args asset.AssetServiceUpdateAssetArgs
	_args.Req = req
	var _result asset.AssetServiceUpdateAssetResult
	if err = p.c.Call(ctx, "UpdateAsset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAsset(ctx context.Context, req *asset.GetAssetReq) (r *asset.GetAssetResp, err error) {
	var _args asset.AssetServiceGetAssetArgs
	_args.Req = req
	var _result asset.AssetServiceGetAssetResult
	if err = p.c.Call(ctx, "GetAsset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAssets(ctx context.Context, req *asset.ListAssetsReq) (r *asset.ListAssetsResp, err error) {
	var _args asset.AssetServiceListAssetsArgs
	_args.Req = req
	var _result asset.AssetServiceListAssetsResult
	if err = p.c.Call(ctx, "ListAssets", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetAssetLibraryState(ctx context.Context, req *asset.SetAssetLibraryStateReq) (r *asset.SetAssetLibraryStateResp, err error) {
	var _args asset.AssetServiceSetAssetLibraryStateArgs
	_args.Req = req
	var _result asset.AssetServiceSetAssetLibraryStateResult
	if err = p.c.Call(ctx, "SetAssetLibraryState", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAsset(ctx context.Context, req *asset.DeleteAssetReq) (r *asset.DeleteAssetResp, err error) {
	var _args asset.AssetServiceDeleteAssetArgs
	_args.Req = req
	var _result asset.AssetServiceDeleteAssetResult
	if err = p.c.Call(ctx, "DeleteAsset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAssetVersion(ctx context.Context, req *asset.CreateAssetVersionReq) (r *asset.CreateAssetVersionResp, err error) {
	var _args asset.AssetServiceCreateAssetVersionArgs
	_args.Req = req
	var _result asset.AssetServiceCreateAssetVersionResult
	if err = p.c.Call(ctx, "CreateAssetVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CopyAssetVersion(ctx context.Context, req *asset.CopyAssetVersionReq) (r *asset.CopyAssetVersionResp, err error) {
	var _args asset.AssetServiceCopyAssetVersionArgs
	_args.Req = req
	var _result asset.AssetServiceCopyAssetVersionResult
	if err = p.c.Call(ctx, "CopyAssetVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAssetVersion(ctx context.Context, req *asset.GetAssetVersionReq) (r *asset.GetAssetVersionResp, err error) {
	var _args asset.AssetServiceGetAssetVersionArgs
	_args.Req = req
	var _result asset.AssetServiceGetAssetVersionResult
	if err = p.c.Call(ctx, "GetAssetVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCurrentAssetVersion(ctx context.Context, req *asset.GetCurrentAssetVersionReq) (r *asset.GetCurrentAssetVersionResp, err error) {
	var _args asset.AssetServiceGetCurrentAssetVersionArgs
	_args.Req = req
	var _result asset.AssetServiceGetCurrentAssetVersionResult
	if err = p.c.Call(ctx, "GetCurrentAssetVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAssetVersions(ctx context.Context, req *asset.ListAssetVersionsReq) (r *asset.ListAssetVersionsResp, err error) {
	var _args asset.AssetServiceListAssetVersionsArgs
	_args.Req = req
	var _result asset.AssetServiceListAssetVersionsResult
	if err = p.c.Call(ctx, "ListAssetVersions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetCurrentAssetVersion(ctx context.Context, req *asset.SetCurrentAssetVersionReq) (r *asset.SetCurrentAssetVersionResp, err error) {
	var _args asset.AssetServiceSetCurrentAssetVersionArgs
	_args.Req = req
	var _result asset.AssetServiceSetCurrentAssetVersionResult
	if err = p.c.Call(ctx, "SetCurrentAssetVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
