// Code generated by Kitex v0.16.1. DO NOT EDIT.

package assetservice

import (
	"context"
	asset "github.com/castlexu/micro-service/services/edge-api/kitex_gen/asset"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Health(ctx context.Context, req *asset.HealthReq, callOptions ...callopt.Option) (r *asset.HealthResp, err error)
	CreateAssetType(ctx context.Context, req *asset.CreateAssetTypeReq, callOptions ...callopt.Option) (r *asset.CreateAssetTypeResp, err error)
	UpdateAssetType(ctx context.Context, req *asset.UpdateAssetTypeReq, callOptions ...callopt.Option) (r *asset.UpdateAssetTypeResp, err error)
	GetAssetType(ctx context.Context, req *asset.GetAssetTypeReq, callOptions ...callopt.Option) (r *asset.GetAssetTypeResp, err error)
	ListAssetTypes(ctx context.Context, req *asset.ListAssetTypesReq, callOptions ...callopt.Option) (r *asset.ListAssetTypesResp, err error)
	DeleteAssetType(ctx context.Context, req *asset.DeleteAssetTypeReq, callOptions ...callopt.Option) (r *asset.DeleteAssetTypeResp, err error)
	CreateAssetCategory(ctx context.Context, req *asset.CreateAssetCategoryReq, callOptions ...callopt.Option) (r *asset.CreateAssetCategoryResp, err error)
	UpdateAssetCategory(ctx context.Context, req *asset.UpdateAssetCategoryReq, callOptions ...callopt.Option) (r *asset.UpdateAssetCategoryResp, err error)
	ListAssetCategories(ctx context.Context, req *asset.ListAssetCategoriesReq, callOptions ...callopt.Option) (r *asset.ListAssetCategoriesResp, err error)
	DeleteAssetCategory(ctx context.Context, req *asset.DeleteAssetCategoryReq, callOptions ...callopt.Option) (r *asset.DeleteAssetCategoryResp, err error)
	CreateAsset(ctx context.Context, req *asset.CreateAssetReq, callOptions ...callopt.Option) (r *asset.CreateAssetResp, err error)
	UpdateAsset(ctx context.Context, req *asset.UpdateAssetReq, callOptions ...callopt.Option) (r *asset.UpdateAssetResp, err error)
	GetAsset(ctx context.Context, req *asset.GetAssetReq, callOptions ...callopt.Option) (r *asset.GetAssetResp, err error)
	ListAssets(ctx context.Context, req *asset.ListAssetsReq, callOptions ...callopt.Option) (r *asset.ListAssetsResp, err error)
	SetAssetLibraryState(ctx context.Context, req *asset.SetAssetLibraryStateReq, callOptions ...callopt.Option) (r *asset.SetAssetLibraryStateResp, err error)
	DeleteAsset(ctx context.Context, req *asset.DeleteAssetReq, callOptions ...callopt.Option) (r *asset.DeleteAssetResp, err error)
	CreateAssetVersion(ctx context.Context, req *asset.CreateAssetVersionReq, callOptions ...callopt.Option) (r *asset.CreateAssetVersionResp, err error)
	CopyAssetVersion(ctx context.Context, req *asset.CopyAssetVersionReq, callOptions ...callopt.Option) (r *asset.CopyAssetVersionResp, err error)
	GetAssetVersion(ctx context.Context, req *asset.GetAssetVersionReq, callOptions ...callopt.Option) (r *asset.GetAssetVersionResp, err error)
	GetCurrentAssetVersion(ctx context.Context, req *asset.GetCurrentAssetVersionReq, callOptions ...callopt.Option) (r *asset.GetCurrentAssetVersionResp, err error)
	ListAssetVersions(ctx context.Context, req *asset.ListAssetVersionsReq, callOptions ...callopt.Option) (r *asset.ListAssetVersionsResp, err error)
	SetCurrentAssetVersion(ctx context.Context, req *asset.SetCurrentAssetVersionReq, callOptions ...callopt.Option) (r *asset.SetCurrentAssetVersionResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAssetServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAssetServiceClient struct {
	*kClient
}

func (p *kAssetServiceClient) Health(ctx context.Context, req *asset.HealthReq, callOptions ...callopt.Option) (r *asset.HealthResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx, req)
}

func (p *kAssetServiceClient) CreateAssetType(ctx context.Context, req *asset.CreateAssetTypeReq, callOptions ...callopt.Option) (r *asset.CreateAssetTypeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAssetType(ctx, req)
}

func (p *kAssetServiceClient) UpdateAssetType(ctx context.Context, req *asset.UpdateAssetTypeReq, callOptions ...callopt.Option) (r *asset.UpdateAssetTypeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAssetType(ctx, req)
}

func (p *kAssetServiceClient) GetAssetType(ctx context.Context, req *asset.GetAssetTypeReq, callOptions ...callopt.Option) (r *asset.GetAssetTypeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAssetType(ctx, req)
}

func (p *kAssetServiceClient) ListAssetTypes(ctx context.Context, req *asset.ListAssetTypesReq, callOptions ...callopt.Option) (r *asset.ListAssetTypesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAssetTypes(ctx, req)
}

func (p *kAssetServiceClient) DeleteAssetType(ctx context.Context, req *asset.DeleteAssetTypeReq, callOptions ...callopt.Option) (r *asset.DeleteAssetTypeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAssetType(ctx, req)
}

func (p *kAssetServiceClient) CreateAssetCategory(ctx context.Context, req *asset.CreateAssetCategoryReq, callOptions ...callopt.Option) (r *asset.CreateAssetCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAssetCategory(ctx, req)
}

func (p *kAssetServiceClient) UpdateAssetCategory(ctx context.Context, req *asset.UpdateAssetCategoryReq, callOptions ...callopt.Option) (r *asset.UpdateAssetCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAssetCategory(ctx, req)
}

func (p *kAssetServiceClient) ListAssetCategories(ctx context.Context, req *asset.ListAssetCategoriesReq, callOptions ...callopt.Option) (r *asset.ListAssetCategoriesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAssetCategories(ctx, req)
}

func (p *kAssetServiceClient) DeleteAssetCategory(ctx context.Context, req *asset.DeleteAssetCategoryReq, callOptions ...callopt.Option) (r *asset.DeleteAssetCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAssetCategory(ctx, req)
}

func (p *kAssetServiceClient) CreateAsset(ctx context.Context, req *asset.CreateAssetReq, callOptions ...callopt.Option) (r *asset.CreateAssetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAsset(ctx, req)
}

func (p *kAssetServiceClient) UpdateAsset(ctx context.Context, req *asset.UpdateAssetReq, callOptions ...callopt.Option) (r *asset.UpdateAssetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAsset(ctx, req)
}

func (p *kAssetServiceClient) GetAsset(ctx context.Context, req *asset.GetAssetReq, callOptions ...callopt.Option) (r *asset.GetAssetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAsset(ctx, req)
}

func (p *kAssetServiceClient) ListAssets(ctx context.Context, req *asset.ListAssetsReq, callOptions ...callopt.Option) (r *asset.ListAssetsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAssets(ctx, req)
}

func (p *kAssetServiceClient) SetAssetLibraryState(ctx context.Context, req *asset.SetAssetLibraryStateReq, callOptions ...callopt.Option) (r *asset.SetAssetLibraryStateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetAssetLibraryState(ctx, req)
}

func (p *kAssetServiceClient) DeleteAsset(ctx context.Context, req *asset.DeleteAssetReq, callOptions ...callopt.Option) (r *asset.DeleteAssetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAsset(ctx, req)
}

func (p *kAssetServiceClient) CreateAssetVersion(ctx context.Context, req *asset.CreateAssetVersionReq, callOptions ...callopt.Option) (r *asset.CreateAssetVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAssetVersion(ctx, req)
}

func (p *kAssetServiceClient) CopyAssetVersion(ctx context.Context, req *asset.CopyAssetVersionReq, callOptions ...callopt.Option) (r *asset.CopyAssetVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CopyAssetVersion(ctx, req)
}

func (p *kAssetServiceClient) GetAssetVersion(ctx context.Context, req *asset.GetAssetVersionReq, callOptions ...callopt.Option) (r *asset.GetAssetVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAssetVersion(ctx, req)
}

func (p *kAssetServiceClient) GetCurrentAssetVersion(ctx context.Context, req *asset.GetCurrentAssetVersionReq, callOptions ...callopt.Option) (r *asset.GetCurrentAssetVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCurrentAssetVersion(ctx, req)
}

func (p *kAssetServiceClient) ListAssetVersions(ctx context.Context, req *asset.ListAssetVersionsReq, callOptions ...callopt.Option) (r *asset.ListAssetVersionsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAssetVersions(ctx, req)
}

func (p *kAssetServiceClient) SetCurrentAssetVersion(ctx context.Context, req *asset.SetCurrentAssetVersionReq, callOptions ...callopt.Option) (r *asset.SetCurrentAssetVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetCurrentAssetVersion(ctx, req)
}
