// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package iam

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/castlexu/micro-service/services/idp/kitex_gen/base"
)

type UserStatus int64

const (
	UserStatus_UNKNOWN  UserStatus = 0
	UserStatus_ACTIVE   UserStatus = 1
	UserStatus_DISABLED UserStatus = 2
	UserStatus_BANNED   UserStatus = 3
)

func (p UserStatus) String() string {
	switch p {
	case UserStatus_UNKNOWN:
		return "UNKNOWN"
	case UserStatus_ACTIVE:
		return "ACTIVE"
	case UserStatus_DISABLED:
		return "DISABLED"
	case UserStatus_BANNED:
		return "BANNED"
	}
	return "<UNSET>"
}

func UserStatusFromString(s string) (UserStatus, error) {
	switch s {
	case "UNKNOWN":
		return UserStatus_UNKNOWN, nil
	case "ACTIVE":
		return UserStatus_ACTIVE, nil
	case "DISABLED":
		return UserStatus_DISABLED, nil
	case "BANNED":
		return UserStatus_BANNED, nil
	}
	return UserStatus(0), fmt.Errorf("not a valid UserStatus string")
}

func UserStatusPtr(v UserStatus) *UserStatus { return &v }
func (p *UserStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = UserStatus(result.Int64)
	return
}

func (p *UserStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ProviderProfile struct {
	Provider    string  `thrift:"Provider,1,required" frugal:"1,required,string" json:"Provider"`
	ProviderSub string  `thrift:"ProviderSub,2,required" frugal:"2,required,string" json:"ProviderSub"`
	Email       string  `thrift:"Email,3,required" frugal:"3,required,string" json:"Email"`
	Name        *string `thrift:"Name,4,optional" frugal:"4,optional,string" json:"Name,omitempty"`
	AvatarURL   *string `thrift:"AvatarURL,5,optional" frugal:"5,optional,string" json:"AvatarURL,omitempty"`
}

func NewProviderProfile() *ProviderProfile {
	return &ProviderProfile{}
}

func (p *ProviderProfile) InitDefault() {
}

func (p *ProviderProfile) GetProvider() (v string) {
	return p.Provider
}

func (p *ProviderProfile) GetProviderSub() (v string) {
	return p.ProviderSub
}

func (p *ProviderProfile) GetEmail() (v string) {
	return p.Email
}

var ProviderProfile_Name_DEFAULT string

func (p *ProviderProfile) GetName() (v string) {
	if !p.IsSetName() {
		return ProviderProfile_Name_DEFAULT
	}
	return *p.Name
}

var ProviderProfile_AvatarURL_DEFAULT string

func (p *ProviderProfile) GetAvatarURL() (v string) {
	if !p.IsSetAvatarURL() {
		return ProviderProfile_AvatarURL_DEFAULT
	}
	return *p.AvatarURL
}
func (p *ProviderProfile) SetProvider(val string) {
	p.Provider = val
}
func (p *ProviderProfile) SetProviderSub(val string) {
	p.ProviderSub = val
}
func (p *ProviderProfile) SetEmail(val string) {
	p.Email = val
}
func (p *ProviderProfile) SetName(val *string) {
	p.Name = val
}
func (p *ProviderProfile) SetAvatarURL(val *string) {
	p.AvatarURL = val
}

func (p *ProviderProfile) IsSetName() bool {
	return p.Name != nil
}

func (p *ProviderProfile) IsSetAvatarURL() bool {
	return p.AvatarURL != nil
}

func (p *ProviderProfile) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProviderProfile(%+v)", *p)
}

var fieldIDToName_ProviderProfile = map[int16]string{
	1: "Provider",
	2: "ProviderSub",
	3: "Email",
	4: "Name",
	5: "AvatarURL",
}

type UpsertUserByProviderReq struct {
	Base    *base.BaseReq    `thrift:"Base,1,required" frugal:"1,required,base.BaseReq" json:"Base"`
	Profile *ProviderProfile `thrift:"Profile,2,required" frugal:"2,required,ProviderProfile" json:"Profile"`
}

func NewUpsertUserByProviderReq() *UpsertUserByProviderReq {
	return &UpsertUserByProviderReq{}
}

func (p *UpsertUserByProviderReq) InitDefault() {
}

var UpsertUserByProviderReq_Base_DEFAULT *base.BaseReq

func (p *UpsertUserByProviderReq) GetBase() (v *base.BaseReq) {
	if !p.IsSetBase() {
		return UpsertUserByProviderReq_Base_DEFAULT
	}
	return p.Base
}

var UpsertUserByProviderReq_Profile_DEFAULT *ProviderProfile

func (p *UpsertUserByProviderReq) GetProfile() (v *ProviderProfile) {
	if !p.IsSetProfile() {
		return UpsertUserByProviderReq_Profile_DEFAULT
	}
	return p.Profile
}
func (p *UpsertUserByProviderReq) SetBase(val *base.BaseReq) {
	p.Base = val
}
func (p *UpsertUserByProviderReq) SetProfile(val *ProviderProfile) {
	p.Profile = val
}

func (p *UpsertUserByProviderReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpsertUserByProviderReq) IsSetProfile() bool {
	return p.Profile != nil
}

func (p *UpsertUserByProviderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpsertUserByProviderReq(%+v)", *p)
}

var fieldIDToName_UpsertUserByProviderReq = map[int16]string{
	1: "Base",
	2: "Profile",
}

type UpsertUserByProviderResp struct {
	Base    *base.BaseResp `thrift:"Base,1,required" frugal:"1,required,base.BaseResp" json:"Base"`
	UserID  string         `thrift:"UserID,2,required" frugal:"2,required,string" json:"UserID"`
	Created bool           `thrift:"Created,3,required" frugal:"3,required,bool" json:"Created"`
}

func NewUpsertUserByProviderResp() *UpsertUserByProviderResp {
	return &UpsertUserByProviderResp{}
}

func (p *UpsertUserByProviderResp) InitDefault() {
}

var UpsertUserByProviderResp_Base_DEFAULT *base.BaseResp

func (p *UpsertUserByProviderResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return UpsertUserByProviderResp_Base_DEFAULT
	}
	return p.Base
}

func (p *UpsertUserByProviderResp) GetUserID() (v string) {
	return p.UserID
}

func (p *UpsertUserByProviderResp) GetCreated() (v bool) {
	return p.Created
}
func (p *UpsertUserByProviderResp) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *UpsertUserByProviderResp) SetUserID(val string) {
	p.UserID = val
}
func (p *UpsertUserByProviderResp) SetCreated(val bool) {
	p.Created = val
}

func (p *UpsertUserByProviderResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpsertUserByProviderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpsertUserByProviderResp(%+v)", *p)
}

var fieldIDToName_UpsertUserByProviderResp = map[int16]string{
	1: "Base",
	2: "UserID",
	3: "Created",
}

type GetUserReq struct {
	Base   *base.BaseReq `thrift:"Base,1,required" frugal:"1,required,base.BaseReq" json:"Base"`
	UserID string        `thrift:"UserID,2,required" frugal:"2,required,string" json:"UserID"`
}

func NewGetUserReq() *GetUserReq {
	return &GetUserReq{}
}

func (p *GetUserReq) InitDefault() {
}

var GetUserReq_Base_DEFAULT *base.BaseReq

func (p *GetUserReq) GetBase() (v *base.BaseReq) {
	if !p.IsSetBase() {
		return GetUserReq_Base_DEFAULT
	}
	return p.Base
}

func (p *GetUserReq) GetUserID() (v string) {
	return p.UserID
}
func (p *GetUserReq) SetBase(val *base.BaseReq) {
	p.Base = val
}
func (p *GetUserReq) SetUserID(val string) {
	p.UserID = val
}

func (p *GetUserReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserReq(%+v)", *p)
}

var fieldIDToName_GetUserReq = map[int16]string{
	1: "Base",
	2: "UserID",
}

type GetUserResp struct {
	Base      *base.BaseResp `thrift:"Base,1,required" frugal:"1,required,base.BaseResp" json:"Base"`
	UserID    string         `thrift:"UserID,2,required" frugal:"2,required,string" json:"UserID"`
	Email     string         `thrift:"Email,3,required" frugal:"3,required,string" json:"Email"`
	Name      *string        `thrift:"Name,4,optional" frugal:"4,optional,string" json:"Name,omitempty"`
	AvatarURL *string        `thrift:"AvatarURL,5,optional" frugal:"5,optional,string" json:"AvatarURL,omitempty"`
	Status    UserStatus     `thrift:"Status,6,required" frugal:"6,required,UserStatus" json:"Status"`
	CreatedAt int64          `thrift:"CreatedAt,7,required" frugal:"7,required,i64" json:"CreatedAt"`
}

func NewGetUserResp() *GetUserResp {
	return &GetUserResp{}
}

func (p *GetUserResp) InitDefault() {
}

var GetUserResp_Base_DEFAULT *base.BaseResp

func (p *GetUserResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return GetUserResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetUserResp) GetUserID() (v string) {
	return p.UserID
}

func (p *GetUserResp) GetEmail() (v string) {
	return p.Email
}

var GetUserResp_Name_DEFAULT string

func (p *GetUserResp) GetName() (v string) {
	if !p.IsSetName() {
		return GetUserResp_Name_DEFAULT
	}
	return *p.Name
}

var GetUserResp_AvatarURL_DEFAULT string

func (p *GetUserResp) GetAvatarURL() (v string) {
	if !p.IsSetAvatarURL() {
		return GetUserResp_AvatarURL_DEFAULT
	}
	return *p.AvatarURL
}

func (p *GetUserResp) GetStatus() (v UserStatus) {
	return p.Status
}

func (p *GetUserResp) GetCreatedAt() (v int64) {
	return p.CreatedAt
}
func (p *GetUserResp) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *GetUserResp) SetUserID(val string) {
	p.UserID = val
}
func (p *GetUserResp) SetEmail(val string) {
	p.Email = val
}
func (p *GetUserResp) SetName(val *string) {
	p.Name = val
}
func (p *GetUserResp) SetAvatarURL(val *string) {
	p.AvatarURL = val
}
func (p *GetUserResp) SetStatus(val UserStatus) {
	p.Status = val
}
func (p *GetUserResp) SetCreatedAt(val int64) {
	p.CreatedAt = val
}

func (p *GetUserResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetUserResp) IsSetName() bool {
	return p.Name != nil
}

func (p *GetUserResp) IsSetAvatarURL() bool {
	return p.AvatarURL != nil
}

func (p *GetUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResp(%+v)", *p)
}

var fieldIDToName_GetUserResp = map[int16]string{
	1: "Base",
	2: "UserID",
	3: "Email",
	4: "Name",
	5: "AvatarURL",
	6: "Status",
	7: "CreatedAt",
}

type IAMService interface {
	UpsertUserByProvider(ctx context.Context, req *UpsertUserByProviderReq) (r *UpsertUserByProviderResp, err error)

	GetUser(ctx context.Context, req *GetUserReq) (r *GetUserResp, err error)
}

type IAMServiceUpsertUserByProviderArgs struct {
	Req *UpsertUserByProviderReq `thrift:"req,1" frugal:"1,default,UpsertUserByProviderReq" json:"req"`
}

func NewIAMServiceUpsertUserByProviderArgs() *IAMServiceUpsertUserByProviderArgs {
	return &IAMServiceUpsertUserByProviderArgs{}
}

func (p *IAMServiceUpsertUserByProviderArgs) InitDefault() {
}

var IAMServiceUpsertUserByProviderArgs_Req_DEFAULT *UpsertUserByProviderReq

func (p *IAMServiceUpsertUserByProviderArgs) GetReq() (v *UpsertUserByProviderReq) {
	if !p.IsSetReq() {
		return IAMServiceUpsertUserByProviderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IAMServiceUpsertUserByProviderArgs) SetReq(val *UpsertUserByProviderReq) {
	p.Req = val
}

func (p *IAMServiceUpsertUserByProviderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IAMServiceUpsertUserByProviderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IAMServiceUpsertUserByProviderArgs(%+v)", *p)
}

var fieldIDToName_IAMServiceUpsertUserByProviderArgs = map[int16]string{
	1: "req",
}

type IAMServiceUpsertUserByProviderResult struct {
	Success *UpsertUserByProviderResp `thrift:"success,0,optional" frugal:"0,optional,UpsertUserByProviderResp" json:"success,omitempty"`
}

func NewIAMServiceUpsertUserByProviderResult() *IAMServiceUpsertUserByProviderResult {
	return &IAMServiceUpsertUserByProviderResult{}
}

func (p *IAMServiceUpsertUserByProviderResult) InitDefault() {
}

var IAMServiceUpsertUserByProviderResult_Success_DEFAULT *UpsertUserByProviderResp

func (p *IAMServiceUpsertUserByProviderResult) GetSuccess() (v *UpsertUserByProviderResp) {
	if !p.IsSetSuccess() {
		return IAMServiceUpsertUserByProviderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IAMServiceUpsertUserByProviderResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpsertUserByProviderResp)
}

func (p *IAMServiceUpsertUserByProviderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IAMServiceUpsertUserByProviderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IAMServiceUpsertUserByProviderResult(%+v)", *p)
}

var fieldIDToName_IAMServiceUpsertUserByProviderResult = map[int16]string{
	0: "success",
}

type IAMServiceGetUserArgs struct {
	Req *GetUserReq `thrift:"req,1" frugal:"1,default,GetUserReq" json:"req"`
}

func NewIAMServiceGetUserArgs() *IAMServiceGetUserArgs {
	return &IAMServiceGetUserArgs{}
}

func (p *IAMServiceGetUserArgs) InitDefault() {
}

var IAMServiceGetUserArgs_Req_DEFAULT *GetUserReq

func (p *IAMServiceGetUserArgs) GetReq() (v *GetUserReq) {
	if !p.IsSetReq() {
		return IAMServiceGetUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IAMServiceGetUserArgs) SetReq(val *GetUserReq) {
	p.Req = val
}

func (p *IAMServiceGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IAMServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IAMServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_IAMServiceGetUserArgs = map[int16]string{
	1: "req",
}

type IAMServiceGetUserResult struct {
	Success *GetUserResp `thrift:"success,0,optional" frugal:"0,optional,GetUserResp" json:"success,omitempty"`
}

func NewIAMServiceGetUserResult() *IAMServiceGetUserResult {
	return &IAMServiceGetUserResult{}
}

func (p *IAMServiceGetUserResult) InitDefault() {
}

var IAMServiceGetUserResult_Success_DEFAULT *GetUserResp

func (p *IAMServiceGetUserResult) GetSuccess() (v *GetUserResp) {
	if !p.IsSetSuccess() {
		return IAMServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IAMServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResp)
}

func (p *IAMServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IAMServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IAMServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_IAMServiceGetUserResult = map[int16]string{
	0: "success",
}
