// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package base

import (
	"fmt"
)

type BaseReq struct {
	TraceID  *string           `thrift:"TraceID,1,optional" frugal:"1,optional,string" json:"TraceID,omitempty"`
	Caller   *string           `thrift:"Caller,2,optional" frugal:"2,optional,string" json:"Caller,omitempty"`
	UserID   *string           `thrift:"UserID,3,optional" frugal:"3,optional,string" json:"UserID,omitempty"`
	TenantID *string           `thrift:"TenantID,4,optional" frugal:"4,optional,string" json:"TenantID,omitempty"`
	Extra    map[string]string `thrift:"Extra,5,optional" frugal:"5,optional,map<string:string>" json:"Extra,omitempty"`
}

func NewBaseReq() *BaseReq {
	return &BaseReq{}
}

func (p *BaseReq) InitDefault() {
}

var BaseReq_TraceID_DEFAULT string

func (p *BaseReq) GetTraceID() (v string) {
	if !p.IsSetTraceID() {
		return BaseReq_TraceID_DEFAULT
	}
	return *p.TraceID
}

var BaseReq_Caller_DEFAULT string

func (p *BaseReq) GetCaller() (v string) {
	if !p.IsSetCaller() {
		return BaseReq_Caller_DEFAULT
	}
	return *p.Caller
}

var BaseReq_UserID_DEFAULT string

func (p *BaseReq) GetUserID() (v string) {
	if !p.IsSetUserID() {
		return BaseReq_UserID_DEFAULT
	}
	return *p.UserID
}

var BaseReq_TenantID_DEFAULT string

func (p *BaseReq) GetTenantID() (v string) {
	if !p.IsSetTenantID() {
		return BaseReq_TenantID_DEFAULT
	}
	return *p.TenantID
}

var BaseReq_Extra_DEFAULT map[string]string

func (p *BaseReq) GetExtra() (v map[string]string) {
	if !p.IsSetExtra() {
		return BaseReq_Extra_DEFAULT
	}
	return p.Extra
}
func (p *BaseReq) SetTraceID(val *string) {
	p.TraceID = val
}
func (p *BaseReq) SetCaller(val *string) {
	p.Caller = val
}
func (p *BaseReq) SetUserID(val *string) {
	p.UserID = val
}
func (p *BaseReq) SetTenantID(val *string) {
	p.TenantID = val
}
func (p *BaseReq) SetExtra(val map[string]string) {
	p.Extra = val
}

func (p *BaseReq) IsSetTraceID() bool {
	return p.TraceID != nil
}

func (p *BaseReq) IsSetCaller() bool {
	return p.Caller != nil
}

func (p *BaseReq) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *BaseReq) IsSetTenantID() bool {
	return p.TenantID != nil
}

func (p *BaseReq) IsSetExtra() bool {
	return p.Extra != nil
}

func (p *BaseReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseReq(%+v)", *p)
}

var fieldIDToName_BaseReq = map[int16]string{
	1: "TraceID",
	2: "Caller",
	3: "UserID",
	4: "TenantID",
	5: "Extra",
}

type PageReq struct {
	PageNum  int32 `thrift:"PageNum,1,required" frugal:"1,required,i32" json:"PageNum"`
	PageSize int32 `thrift:"PageSize,2,required" frugal:"2,required,i32" json:"PageSize"`
}

func NewPageReq() *PageReq {
	return &PageReq{
		PageNum:  1,
		PageSize: 20,
	}
}

func (p *PageReq) InitDefault() {
	p.PageNum = 1
	p.PageSize = 20
}

func (p *PageReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *PageReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *PageReq) SetPageNum(val int32) {
	p.PageNum = val
}
func (p *PageReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *PageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageReq(%+v)", *p)
}

var fieldIDToName_PageReq = map[int16]string{
	1: "PageNum",
	2: "PageSize",
}

type PageResp struct {
	Total      int32 `thrift:"Total,1,required" frugal:"1,required,i32" json:"Total"`
	PageNum    int32 `thrift:"PageNum,2,required" frugal:"2,required,i32" json:"PageNum"`
	PageSize   int32 `thrift:"PageSize,3,required" frugal:"3,required,i32" json:"PageSize"`
	TotalPages int32 `thrift:"TotalPages,4,required" frugal:"4,required,i32" json:"TotalPages"`
}

func NewPageResp() *PageResp {
	return &PageResp{}
}

func (p *PageResp) InitDefault() {
}

func (p *PageResp) GetTotal() (v int32) {
	return p.Total
}

func (p *PageResp) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *PageResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *PageResp) GetTotalPages() (v int32) {
	return p.TotalPages
}
func (p *PageResp) SetTotal(val int32) {
	p.Total = val
}
func (p *PageResp) SetPageNum(val int32) {
	p.PageNum = val
}
func (p *PageResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *PageResp) SetTotalPages(val int32) {
	p.TotalPages = val
}

func (p *PageResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageResp(%+v)", *p)
}

var fieldIDToName_PageResp = map[int16]string{
	1: "Total",
	2: "PageNum",
	3: "PageSize",
	4: "TotalPages",
}

type BaseResp struct {
	Code     int32             `thrift:"Code,1,required" frugal:"1,required,i32" json:"Code"`
	Message  string            `thrift:"Message,2,required" frugal:"2,required,string" json:"Message"`
	Metadata map[string]string `thrift:"Metadata,3,optional" frugal:"3,optional,map<string:string>" json:"Metadata,omitempty"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{
		Code:    0,
		Message: "",
	}
}

func (p *BaseResp) InitDefault() {
	p.Code = 0
	p.Message = ""
}

func (p *BaseResp) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResp) GetMessage() (v string) {
	return p.Message
}

var BaseResp_Metadata_DEFAULT map[string]string

func (p *BaseResp) GetMetadata() (v map[string]string) {
	if !p.IsSetMetadata() {
		return BaseResp_Metadata_DEFAULT
	}
	return p.Metadata
}
func (p *BaseResp) SetCode(val int32) {
	p.Code = val
}
func (p *BaseResp) SetMessage(val string) {
	p.Message = val
}
func (p *BaseResp) SetMetadata(val map[string]string) {
	p.Metadata = val
}

func (p *BaseResp) IsSetMetadata() bool {
	return p.Metadata != nil
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "Code",
	2: "Message",
	3: "Metadata",
}
