// Code generated by Kitex v0.16.1. DO NOT EDIT.

package iamservice

import (
	"context"
	"errors"
	iam "github.com/castlexu/micro-service/services/iam/kitex_gen/iam"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UpsertUserByProvider": kitex.NewMethodInfo(
		upsertUserByProviderHandler,
		newIAMServiceUpsertUserByProviderArgs,
		newIAMServiceUpsertUserByProviderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUser": kitex.NewMethodInfo(
		getUserHandler,
		newIAMServiceGetUserArgs,
		newIAMServiceGetUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	iAMServiceServiceInfo                = NewServiceInfo()
	iAMServiceServiceInfoForClient       = NewServiceInfoForClient()
	iAMServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return iAMServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return iAMServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return iAMServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "IAMService"
	handlerType := (*iam.IAMService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "iam",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func upsertUserByProviderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*iam.IAMServiceUpsertUserByProviderArgs)
	realResult := result.(*iam.IAMServiceUpsertUserByProviderResult)
	success, err := handler.(iam.IAMService).UpsertUserByProvider(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIAMServiceUpsertUserByProviderArgs() interface{} {
	return iam.NewIAMServiceUpsertUserByProviderArgs()
}

func newIAMServiceUpsertUserByProviderResult() interface{} {
	return iam.NewIAMServiceUpsertUserByProviderResult()
}

func getUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*iam.IAMServiceGetUserArgs)
	realResult := result.(*iam.IAMServiceGetUserResult)
	success, err := handler.(iam.IAMService).GetUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIAMServiceGetUserArgs() interface{} {
	return iam.NewIAMServiceGetUserArgs()
}

func newIAMServiceGetUserResult() interface{} {
	return iam.NewIAMServiceGetUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UpsertUserByProvider(ctx context.Context, req *iam.UpsertUserByProviderReq) (r *iam.UpsertUserByProviderResp, err error) {
	var _args iam.IAMServiceUpsertUserByProviderArgs
	_args.Req = req
	var _result iam.IAMServiceUpsertUserByProviderResult
	if err = p.c.Call(ctx, "UpsertUserByProvider", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUser(ctx context.Context, req *iam.GetUserReq) (r *iam.GetUserResp, err error) {
	var _args iam.IAMServiceGetUserArgs
	_args.Req = req
	var _result iam.IAMServiceGetUserResult
	if err = p.c.Call(ctx, "GetUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
