// Code generated by Kitex v0.16.1. DO NOT EDIT.

package iamservice

import (
	"context"
	iam "github.com/castlexu/micro-service/services/idp/kitex_gen/iam"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UpsertUserByProvider(ctx context.Context, req *iam.UpsertUserByProviderReq, callOptions ...callopt.Option) (r *iam.UpsertUserByProviderResp, err error)
	GetUser(ctx context.Context, req *iam.GetUserReq, callOptions ...callopt.Option) (r *iam.GetUserResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kIAMServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kIAMServiceClient struct {
	*kClient
}

func (p *kIAMServiceClient) UpsertUserByProvider(ctx context.Context, req *iam.UpsertUserByProviderReq, callOptions ...callopt.Option) (r *iam.UpsertUserByProviderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpsertUserByProvider(ctx, req)
}

func (p *kIAMServiceClient) GetUser(ctx context.Context, req *iam.GetUserReq, callOptions ...callopt.Option) (r *iam.GetUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, req)
}
