// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package idp

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/castlexu/micro-service/services/edge-api/kitex_gen/base"
)

type TokenType int64

const (
	TokenType_UNKNOWN       TokenType = 0
	TokenType_ACCESS_TOKEN  TokenType = 1
	TokenType_REFRESH_TOKEN TokenType = 2
)

func (p TokenType) String() string {
	switch p {
	case TokenType_UNKNOWN:
		return "UNKNOWN"
	case TokenType_ACCESS_TOKEN:
		return "ACCESS_TOKEN"
	case TokenType_REFRESH_TOKEN:
		return "REFRESH_TOKEN"
	}
	return "<UNSET>"
}

func TokenTypeFromString(s string) (TokenType, error) {
	switch s {
	case "UNKNOWN":
		return TokenType_UNKNOWN, nil
	case "ACCESS_TOKEN":
		return TokenType_ACCESS_TOKEN, nil
	case "REFRESH_TOKEN":
		return TokenType_REFRESH_TOKEN, nil
	}
	return TokenType(0), fmt.Errorf("not a valid TokenType string")
}

func TokenTypePtr(v TokenType) *TokenType { return &v }
func (p *TokenType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TokenType(result.Int64)
	return
}

func (p *TokenType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type GetGoogleAuthURLReq struct {
	Base        *base.BaseReq `thrift:"Base,1,required" frugal:"1,required,base.BaseReq" json:"Base"`
	RedirectURI *string       `thrift:"RedirectURI,2,optional" frugal:"2,optional,string" json:"RedirectURI,omitempty"`
}

func NewGetGoogleAuthURLReq() *GetGoogleAuthURLReq {
	return &GetGoogleAuthURLReq{}
}

func (p *GetGoogleAuthURLReq) InitDefault() {
}

var GetGoogleAuthURLReq_Base_DEFAULT *base.BaseReq

func (p *GetGoogleAuthURLReq) GetBase() (v *base.BaseReq) {
	if !p.IsSetBase() {
		return GetGoogleAuthURLReq_Base_DEFAULT
	}
	return p.Base
}

var GetGoogleAuthURLReq_RedirectURI_DEFAULT string

func (p *GetGoogleAuthURLReq) GetRedirectURI() (v string) {
	if !p.IsSetRedirectURI() {
		return GetGoogleAuthURLReq_RedirectURI_DEFAULT
	}
	return *p.RedirectURI
}
func (p *GetGoogleAuthURLReq) SetBase(val *base.BaseReq) {
	p.Base = val
}
func (p *GetGoogleAuthURLReq) SetRedirectURI(val *string) {
	p.RedirectURI = val
}

func (p *GetGoogleAuthURLReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetGoogleAuthURLReq) IsSetRedirectURI() bool {
	return p.RedirectURI != nil
}

func (p *GetGoogleAuthURLReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetGoogleAuthURLReq(%+v)", *p)
}

var fieldIDToName_GetGoogleAuthURLReq = map[int16]string{
	1: "Base",
	2: "RedirectURI",
}

type GetGoogleAuthURLResp struct {
	Base    *base.BaseResp `thrift:"Base,1,required" frugal:"1,required,base.BaseResp" json:"Base"`
	AuthURL string         `thrift:"AuthURL,2,required" frugal:"2,required,string" json:"AuthURL"`
	State   string         `thrift:"State,3,required" frugal:"3,required,string" json:"State"`
}

func NewGetGoogleAuthURLResp() *GetGoogleAuthURLResp {
	return &GetGoogleAuthURLResp{}
}

func (p *GetGoogleAuthURLResp) InitDefault() {
}

var GetGoogleAuthURLResp_Base_DEFAULT *base.BaseResp

func (p *GetGoogleAuthURLResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return GetGoogleAuthURLResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetGoogleAuthURLResp) GetAuthURL() (v string) {
	return p.AuthURL
}

func (p *GetGoogleAuthURLResp) GetState() (v string) {
	return p.State
}
func (p *GetGoogleAuthURLResp) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *GetGoogleAuthURLResp) SetAuthURL(val string) {
	p.AuthURL = val
}
func (p *GetGoogleAuthURLResp) SetState(val string) {
	p.State = val
}

func (p *GetGoogleAuthURLResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetGoogleAuthURLResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetGoogleAuthURLResp(%+v)", *p)
}

var fieldIDToName_GetGoogleAuthURLResp = map[int16]string{
	1: "Base",
	2: "AuthURL",
	3: "State",
}

type LoginByGoogleReq struct {
	Base        *base.BaseReq `thrift:"Base,1,required" frugal:"1,required,base.BaseReq" json:"Base"`
	Code        string        `thrift:"Code,2,required" frugal:"2,required,string" json:"Code"`
	State       string        `thrift:"State,3,required" frugal:"3,required,string" json:"State"`
	RedirectURI *string       `thrift:"RedirectURI,4,optional" frugal:"4,optional,string" json:"RedirectURI,omitempty"`
}

func NewLoginByGoogleReq() *LoginByGoogleReq {
	return &LoginByGoogleReq{}
}

func (p *LoginByGoogleReq) InitDefault() {
}

var LoginByGoogleReq_Base_DEFAULT *base.BaseReq

func (p *LoginByGoogleReq) GetBase() (v *base.BaseReq) {
	if !p.IsSetBase() {
		return LoginByGoogleReq_Base_DEFAULT
	}
	return p.Base
}

func (p *LoginByGoogleReq) GetCode() (v string) {
	return p.Code
}

func (p *LoginByGoogleReq) GetState() (v string) {
	return p.State
}

var LoginByGoogleReq_RedirectURI_DEFAULT string

func (p *LoginByGoogleReq) GetRedirectURI() (v string) {
	if !p.IsSetRedirectURI() {
		return LoginByGoogleReq_RedirectURI_DEFAULT
	}
	return *p.RedirectURI
}
func (p *LoginByGoogleReq) SetBase(val *base.BaseReq) {
	p.Base = val
}
func (p *LoginByGoogleReq) SetCode(val string) {
	p.Code = val
}
func (p *LoginByGoogleReq) SetState(val string) {
	p.State = val
}
func (p *LoginByGoogleReq) SetRedirectURI(val *string) {
	p.RedirectURI = val
}

func (p *LoginByGoogleReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginByGoogleReq) IsSetRedirectURI() bool {
	return p.RedirectURI != nil
}

func (p *LoginByGoogleReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginByGoogleReq(%+v)", *p)
}

var fieldIDToName_LoginByGoogleReq = map[int16]string{
	1: "Base",
	2: "Code",
	3: "State",
	4: "RedirectURI",
}

type LoginByGoogleResp struct {
	Base         *base.BaseResp `thrift:"Base,1,required" frugal:"1,required,base.BaseResp" json:"Base"`
	AccessToken  string         `thrift:"AccessToken,2,required" frugal:"2,required,string" json:"AccessToken"`
	RefreshToken string         `thrift:"RefreshToken,3,required" frugal:"3,required,string" json:"RefreshToken"`
	ExpiresAt    int64          `thrift:"ExpiresAt,4,required" frugal:"4,required,i64" json:"ExpiresAt"`
	UserID       string         `thrift:"UserID,5,required" frugal:"5,required,string" json:"UserID"`
}

func NewLoginByGoogleResp() *LoginByGoogleResp {
	return &LoginByGoogleResp{}
}

func (p *LoginByGoogleResp) InitDefault() {
}

var LoginByGoogleResp_Base_DEFAULT *base.BaseResp

func (p *LoginByGoogleResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return LoginByGoogleResp_Base_DEFAULT
	}
	return p.Base
}

func (p *LoginByGoogleResp) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *LoginByGoogleResp) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *LoginByGoogleResp) GetExpiresAt() (v int64) {
	return p.ExpiresAt
}

func (p *LoginByGoogleResp) GetUserID() (v string) {
	return p.UserID
}
func (p *LoginByGoogleResp) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *LoginByGoogleResp) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *LoginByGoogleResp) SetRefreshToken(val string) {
	p.RefreshToken = val
}
func (p *LoginByGoogleResp) SetExpiresAt(val int64) {
	p.ExpiresAt = val
}
func (p *LoginByGoogleResp) SetUserID(val string) {
	p.UserID = val
}

func (p *LoginByGoogleResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginByGoogleResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginByGoogleResp(%+v)", *p)
}

var fieldIDToName_LoginByGoogleResp = map[int16]string{
	1: "Base",
	2: "AccessToken",
	3: "RefreshToken",
	4: "ExpiresAt",
	5: "UserID",
}

type RefreshTokenReq struct {
	Base         *base.BaseReq `thrift:"Base,1,required" frugal:"1,required,base.BaseReq" json:"Base"`
	RefreshToken string        `thrift:"RefreshToken,2,required" frugal:"2,required,string" json:"RefreshToken"`
}

func NewRefreshTokenReq() *RefreshTokenReq {
	return &RefreshTokenReq{}
}

func (p *RefreshTokenReq) InitDefault() {
}

var RefreshTokenReq_Base_DEFAULT *base.BaseReq

func (p *RefreshTokenReq) GetBase() (v *base.BaseReq) {
	if !p.IsSetBase() {
		return RefreshTokenReq_Base_DEFAULT
	}
	return p.Base
}

func (p *RefreshTokenReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *RefreshTokenReq) SetBase(val *base.BaseReq) {
	p.Base = val
}
func (p *RefreshTokenReq) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *RefreshTokenReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *RefreshTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenReq(%+v)", *p)
}

var fieldIDToName_RefreshTokenReq = map[int16]string{
	1: "Base",
	2: "RefreshToken",
}

type RefreshTokenResp struct {
	Base         *base.BaseResp `thrift:"Base,1,required" frugal:"1,required,base.BaseResp" json:"Base"`
	AccessToken  string         `thrift:"AccessToken,2,required" frugal:"2,required,string" json:"AccessToken"`
	RefreshToken string         `thrift:"RefreshToken,3,required" frugal:"3,required,string" json:"RefreshToken"`
	ExpiresAt    int64          `thrift:"ExpiresAt,4,required" frugal:"4,required,i64" json:"ExpiresAt"`
}

func NewRefreshTokenResp() *RefreshTokenResp {
	return &RefreshTokenResp{}
}

func (p *RefreshTokenResp) InitDefault() {
}

var RefreshTokenResp_Base_DEFAULT *base.BaseResp

func (p *RefreshTokenResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return RefreshTokenResp_Base_DEFAULT
	}
	return p.Base
}

func (p *RefreshTokenResp) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *RefreshTokenResp) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *RefreshTokenResp) GetExpiresAt() (v int64) {
	return p.ExpiresAt
}
func (p *RefreshTokenResp) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *RefreshTokenResp) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *RefreshTokenResp) SetRefreshToken(val string) {
	p.RefreshToken = val
}
func (p *RefreshTokenResp) SetExpiresAt(val int64) {
	p.ExpiresAt = val
}

func (p *RefreshTokenResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RefreshTokenResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenResp(%+v)", *p)
}

var fieldIDToName_RefreshTokenResp = map[int16]string{
	1: "Base",
	2: "AccessToken",
	3: "RefreshToken",
	4: "ExpiresAt",
}

type VerifyTokenReq struct {
	Base  *base.BaseReq `thrift:"Base,1,required" frugal:"1,required,base.BaseReq" json:"Base"`
	Token string        `thrift:"Token,2,required" frugal:"2,required,string" json:"Token"`
	Type  *TokenType    `thrift:"Type,3,optional" frugal:"3,optional,TokenType" json:"Type,omitempty"`
}

func NewVerifyTokenReq() *VerifyTokenReq {
	return &VerifyTokenReq{}
}

func (p *VerifyTokenReq) InitDefault() {
}

var VerifyTokenReq_Base_DEFAULT *base.BaseReq

func (p *VerifyTokenReq) GetBase() (v *base.BaseReq) {
	if !p.IsSetBase() {
		return VerifyTokenReq_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyTokenReq) GetToken() (v string) {
	return p.Token
}

var VerifyTokenReq_Type_DEFAULT TokenType

func (p *VerifyTokenReq) GetType() (v TokenType) {
	if !p.IsSetType() {
		return VerifyTokenReq_Type_DEFAULT
	}
	return *p.Type
}
func (p *VerifyTokenReq) SetBase(val *base.BaseReq) {
	p.Base = val
}
func (p *VerifyTokenReq) SetToken(val string) {
	p.Token = val
}
func (p *VerifyTokenReq) SetType(val *TokenType) {
	p.Type = val
}

func (p *VerifyTokenReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyTokenReq) IsSetType() bool {
	return p.Type != nil
}

func (p *VerifyTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyTokenReq(%+v)", *p)
}

var fieldIDToName_VerifyTokenReq = map[int16]string{
	1: "Base",
	2: "Token",
	3: "Type",
}

type VerifyTokenResp struct {
	Base      *base.BaseResp `thrift:"Base,1,required" frugal:"1,required,base.BaseResp" json:"Base"`
	UserID    string         `thrift:"UserID,2,required" frugal:"2,required,string" json:"UserID"`
	TenantID  string         `thrift:"TenantID,3,required" frugal:"3,required,string" json:"TenantID"`
	ExpiresAt int64          `thrift:"ExpiresAt,4,required" frugal:"4,required,i64" json:"ExpiresAt"`
}

func NewVerifyTokenResp() *VerifyTokenResp {
	return &VerifyTokenResp{}
}

func (p *VerifyTokenResp) InitDefault() {
}

var VerifyTokenResp_Base_DEFAULT *base.BaseResp

func (p *VerifyTokenResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return VerifyTokenResp_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyTokenResp) GetUserID() (v string) {
	return p.UserID
}

func (p *VerifyTokenResp) GetTenantID() (v string) {
	return p.TenantID
}

func (p *VerifyTokenResp) GetExpiresAt() (v int64) {
	return p.ExpiresAt
}
func (p *VerifyTokenResp) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *VerifyTokenResp) SetUserID(val string) {
	p.UserID = val
}
func (p *VerifyTokenResp) SetTenantID(val string) {
	p.TenantID = val
}
func (p *VerifyTokenResp) SetExpiresAt(val int64) {
	p.ExpiresAt = val
}

func (p *VerifyTokenResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyTokenResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyTokenResp(%+v)", *p)
}

var fieldIDToName_VerifyTokenResp = map[int16]string{
	1: "Base",
	2: "UserID",
	3: "TenantID",
	4: "ExpiresAt",
}

type GetAlipayAuthURLReq struct {
	Base        *base.BaseReq `thrift:"Base,1,required" frugal:"1,required,base.BaseReq" json:"Base"`
	RedirectURI *string       `thrift:"RedirectURI,2,optional" frugal:"2,optional,string" json:"RedirectURI,omitempty"`
}

func NewGetAlipayAuthURLReq() *GetAlipayAuthURLReq {
	return &GetAlipayAuthURLReq{}
}

func (p *GetAlipayAuthURLReq) InitDefault() {
}

var GetAlipayAuthURLReq_Base_DEFAULT *base.BaseReq

func (p *GetAlipayAuthURLReq) GetBase() (v *base.BaseReq) {
	if !p.IsSetBase() {
		return GetAlipayAuthURLReq_Base_DEFAULT
	}
	return p.Base
}

var GetAlipayAuthURLReq_RedirectURI_DEFAULT string

func (p *GetAlipayAuthURLReq) GetRedirectURI() (v string) {
	if !p.IsSetRedirectURI() {
		return GetAlipayAuthURLReq_RedirectURI_DEFAULT
	}
	return *p.RedirectURI
}
func (p *GetAlipayAuthURLReq) SetBase(val *base.BaseReq) {
	p.Base = val
}
func (p *GetAlipayAuthURLReq) SetRedirectURI(val *string) {
	p.RedirectURI = val
}

func (p *GetAlipayAuthURLReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetAlipayAuthURLReq) IsSetRedirectURI() bool {
	return p.RedirectURI != nil
}

func (p *GetAlipayAuthURLReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAlipayAuthURLReq(%+v)", *p)
}

var fieldIDToName_GetAlipayAuthURLReq = map[int16]string{
	1: "Base",
	2: "RedirectURI",
}

type GetAlipayAuthURLResp struct {
	Base    *base.BaseResp `thrift:"Base,1,required" frugal:"1,required,base.BaseResp" json:"Base"`
	AuthURL string         `thrift:"AuthURL,2,required" frugal:"2,required,string" json:"AuthURL"`
	State   string         `thrift:"State,3,required" frugal:"3,required,string" json:"State"`
}

func NewGetAlipayAuthURLResp() *GetAlipayAuthURLResp {
	return &GetAlipayAuthURLResp{}
}

func (p *GetAlipayAuthURLResp) InitDefault() {
}

var GetAlipayAuthURLResp_Base_DEFAULT *base.BaseResp

func (p *GetAlipayAuthURLResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return GetAlipayAuthURLResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetAlipayAuthURLResp) GetAuthURL() (v string) {
	return p.AuthURL
}

func (p *GetAlipayAuthURLResp) GetState() (v string) {
	return p.State
}
func (p *GetAlipayAuthURLResp) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *GetAlipayAuthURLResp) SetAuthURL(val string) {
	p.AuthURL = val
}
func (p *GetAlipayAuthURLResp) SetState(val string) {
	p.State = val
}

func (p *GetAlipayAuthURLResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetAlipayAuthURLResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAlipayAuthURLResp(%+v)", *p)
}

var fieldIDToName_GetAlipayAuthURLResp = map[int16]string{
	1: "Base",
	2: "AuthURL",
	3: "State",
}

type LoginByAlipayReq struct {
	Base     *base.BaseReq `thrift:"Base,1,required" frugal:"1,required,base.BaseReq" json:"Base"`
	AuthCode string        `thrift:"AuthCode,2,required" frugal:"2,required,string" json:"AuthCode"`
	State    string        `thrift:"State,3,required" frugal:"3,required,string" json:"State"`
}

func NewLoginByAlipayReq() *LoginByAlipayReq {
	return &LoginByAlipayReq{}
}

func (p *LoginByAlipayReq) InitDefault() {
}

var LoginByAlipayReq_Base_DEFAULT *base.BaseReq

func (p *LoginByAlipayReq) GetBase() (v *base.BaseReq) {
	if !p.IsSetBase() {
		return LoginByAlipayReq_Base_DEFAULT
	}
	return p.Base
}

func (p *LoginByAlipayReq) GetAuthCode() (v string) {
	return p.AuthCode
}

func (p *LoginByAlipayReq) GetState() (v string) {
	return p.State
}
func (p *LoginByAlipayReq) SetBase(val *base.BaseReq) {
	p.Base = val
}
func (p *LoginByAlipayReq) SetAuthCode(val string) {
	p.AuthCode = val
}
func (p *LoginByAlipayReq) SetState(val string) {
	p.State = val
}

func (p *LoginByAlipayReq) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginByAlipayReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginByAlipayReq(%+v)", *p)
}

var fieldIDToName_LoginByAlipayReq = map[int16]string{
	1: "Base",
	2: "AuthCode",
	3: "State",
}

type LoginByAlipayResp struct {
	Base         *base.BaseResp `thrift:"Base,1,required" frugal:"1,required,base.BaseResp" json:"Base"`
	AccessToken  string         `thrift:"AccessToken,2,required" frugal:"2,required,string" json:"AccessToken"`
	RefreshToken string         `thrift:"RefreshToken,3,required" frugal:"3,required,string" json:"RefreshToken"`
	ExpiresAt    int64          `thrift:"ExpiresAt,4,required" frugal:"4,required,i64" json:"ExpiresAt"`
	UserID       string         `thrift:"UserID,5,required" frugal:"5,required,string" json:"UserID"`
}

func NewLoginByAlipayResp() *LoginByAlipayResp {
	return &LoginByAlipayResp{}
}

func (p *LoginByAlipayResp) InitDefault() {
}

var LoginByAlipayResp_Base_DEFAULT *base.BaseResp

func (p *LoginByAlipayResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return LoginByAlipayResp_Base_DEFAULT
	}
	return p.Base
}

func (p *LoginByAlipayResp) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *LoginByAlipayResp) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *LoginByAlipayResp) GetExpiresAt() (v int64) {
	return p.ExpiresAt
}

func (p *LoginByAlipayResp) GetUserID() (v string) {
	return p.UserID
}
func (p *LoginByAlipayResp) SetBase(val *base.BaseResp) {
	p.Base = val
}
func (p *LoginByAlipayResp) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *LoginByAlipayResp) SetRefreshToken(val string) {
	p.RefreshToken = val
}
func (p *LoginByAlipayResp) SetExpiresAt(val int64) {
	p.ExpiresAt = val
}
func (p *LoginByAlipayResp) SetUserID(val string) {
	p.UserID = val
}

func (p *LoginByAlipayResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginByAlipayResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginByAlipayResp(%+v)", *p)
}

var fieldIDToName_LoginByAlipayResp = map[int16]string{
	1: "Base",
	2: "AccessToken",
	3: "RefreshToken",
	4: "ExpiresAt",
	5: "UserID",
}

type IDPService interface {
	GetGoogleAuthURL(ctx context.Context, req *GetGoogleAuthURLReq) (r *GetGoogleAuthURLResp, err error)

	LoginByGoogle(ctx context.Context, req *LoginByGoogleReq) (r *LoginByGoogleResp, err error)

	GetAlipayAuthURL(ctx context.Context, req *GetAlipayAuthURLReq) (r *GetAlipayAuthURLResp, err error)

	LoginByAlipay(ctx context.Context, req *LoginByAlipayReq) (r *LoginByAlipayResp, err error)

	RefreshToken(ctx context.Context, req *RefreshTokenReq) (r *RefreshTokenResp, err error)

	VerifyToken(ctx context.Context, req *VerifyTokenReq) (r *VerifyTokenResp, err error)
}

type IDPServiceGetGoogleAuthURLArgs struct {
	Req *GetGoogleAuthURLReq `thrift:"req,1" frugal:"1,default,GetGoogleAuthURLReq" json:"req"`
}

func NewIDPServiceGetGoogleAuthURLArgs() *IDPServiceGetGoogleAuthURLArgs {
	return &IDPServiceGetGoogleAuthURLArgs{}
}

func (p *IDPServiceGetGoogleAuthURLArgs) InitDefault() {
}

var IDPServiceGetGoogleAuthURLArgs_Req_DEFAULT *GetGoogleAuthURLReq

func (p *IDPServiceGetGoogleAuthURLArgs) GetReq() (v *GetGoogleAuthURLReq) {
	if !p.IsSetReq() {
		return IDPServiceGetGoogleAuthURLArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IDPServiceGetGoogleAuthURLArgs) SetReq(val *GetGoogleAuthURLReq) {
	p.Req = val
}

func (p *IDPServiceGetGoogleAuthURLArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IDPServiceGetGoogleAuthURLArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceGetGoogleAuthURLArgs(%+v)", *p)
}

var fieldIDToName_IDPServiceGetGoogleAuthURLArgs = map[int16]string{
	1: "req",
}

type IDPServiceGetGoogleAuthURLResult struct {
	Success *GetGoogleAuthURLResp `thrift:"success,0,optional" frugal:"0,optional,GetGoogleAuthURLResp" json:"success,omitempty"`
}

func NewIDPServiceGetGoogleAuthURLResult() *IDPServiceGetGoogleAuthURLResult {
	return &IDPServiceGetGoogleAuthURLResult{}
}

func (p *IDPServiceGetGoogleAuthURLResult) InitDefault() {
}

var IDPServiceGetGoogleAuthURLResult_Success_DEFAULT *GetGoogleAuthURLResp

func (p *IDPServiceGetGoogleAuthURLResult) GetSuccess() (v *GetGoogleAuthURLResp) {
	if !p.IsSetSuccess() {
		return IDPServiceGetGoogleAuthURLResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IDPServiceGetGoogleAuthURLResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetGoogleAuthURLResp)
}

func (p *IDPServiceGetGoogleAuthURLResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IDPServiceGetGoogleAuthURLResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceGetGoogleAuthURLResult(%+v)", *p)
}

var fieldIDToName_IDPServiceGetGoogleAuthURLResult = map[int16]string{
	0: "success",
}

type IDPServiceLoginByGoogleArgs struct {
	Req *LoginByGoogleReq `thrift:"req,1" frugal:"1,default,LoginByGoogleReq" json:"req"`
}

func NewIDPServiceLoginByGoogleArgs() *IDPServiceLoginByGoogleArgs {
	return &IDPServiceLoginByGoogleArgs{}
}

func (p *IDPServiceLoginByGoogleArgs) InitDefault() {
}

var IDPServiceLoginByGoogleArgs_Req_DEFAULT *LoginByGoogleReq

func (p *IDPServiceLoginByGoogleArgs) GetReq() (v *LoginByGoogleReq) {
	if !p.IsSetReq() {
		return IDPServiceLoginByGoogleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IDPServiceLoginByGoogleArgs) SetReq(val *LoginByGoogleReq) {
	p.Req = val
}

func (p *IDPServiceLoginByGoogleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IDPServiceLoginByGoogleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceLoginByGoogleArgs(%+v)", *p)
}

var fieldIDToName_IDPServiceLoginByGoogleArgs = map[int16]string{
	1: "req",
}

type IDPServiceLoginByGoogleResult struct {
	Success *LoginByGoogleResp `thrift:"success,0,optional" frugal:"0,optional,LoginByGoogleResp" json:"success,omitempty"`
}

func NewIDPServiceLoginByGoogleResult() *IDPServiceLoginByGoogleResult {
	return &IDPServiceLoginByGoogleResult{}
}

func (p *IDPServiceLoginByGoogleResult) InitDefault() {
}

var IDPServiceLoginByGoogleResult_Success_DEFAULT *LoginByGoogleResp

func (p *IDPServiceLoginByGoogleResult) GetSuccess() (v *LoginByGoogleResp) {
	if !p.IsSetSuccess() {
		return IDPServiceLoginByGoogleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IDPServiceLoginByGoogleResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginByGoogleResp)
}

func (p *IDPServiceLoginByGoogleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IDPServiceLoginByGoogleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceLoginByGoogleResult(%+v)", *p)
}

var fieldIDToName_IDPServiceLoginByGoogleResult = map[int16]string{
	0: "success",
}

type IDPServiceGetAlipayAuthURLArgs struct {
	Req *GetAlipayAuthURLReq `thrift:"req,1" frugal:"1,default,GetAlipayAuthURLReq" json:"req"`
}

func NewIDPServiceGetAlipayAuthURLArgs() *IDPServiceGetAlipayAuthURLArgs {
	return &IDPServiceGetAlipayAuthURLArgs{}
}

func (p *IDPServiceGetAlipayAuthURLArgs) InitDefault() {
}

var IDPServiceGetAlipayAuthURLArgs_Req_DEFAULT *GetAlipayAuthURLReq

func (p *IDPServiceGetAlipayAuthURLArgs) GetReq() (v *GetAlipayAuthURLReq) {
	if !p.IsSetReq() {
		return IDPServiceGetAlipayAuthURLArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IDPServiceGetAlipayAuthURLArgs) SetReq(val *GetAlipayAuthURLReq) {
	p.Req = val
}

func (p *IDPServiceGetAlipayAuthURLArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IDPServiceGetAlipayAuthURLArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceGetAlipayAuthURLArgs(%+v)", *p)
}

var fieldIDToName_IDPServiceGetAlipayAuthURLArgs = map[int16]string{
	1: "req",
}

type IDPServiceGetAlipayAuthURLResult struct {
	Success *GetAlipayAuthURLResp `thrift:"success,0,optional" frugal:"0,optional,GetAlipayAuthURLResp" json:"success,omitempty"`
}

func NewIDPServiceGetAlipayAuthURLResult() *IDPServiceGetAlipayAuthURLResult {
	return &IDPServiceGetAlipayAuthURLResult{}
}

func (p *IDPServiceGetAlipayAuthURLResult) InitDefault() {
}

var IDPServiceGetAlipayAuthURLResult_Success_DEFAULT *GetAlipayAuthURLResp

func (p *IDPServiceGetAlipayAuthURLResult) GetSuccess() (v *GetAlipayAuthURLResp) {
	if !p.IsSetSuccess() {
		return IDPServiceGetAlipayAuthURLResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IDPServiceGetAlipayAuthURLResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAlipayAuthURLResp)
}

func (p *IDPServiceGetAlipayAuthURLResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IDPServiceGetAlipayAuthURLResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceGetAlipayAuthURLResult(%+v)", *p)
}

var fieldIDToName_IDPServiceGetAlipayAuthURLResult = map[int16]string{
	0: "success",
}

type IDPServiceLoginByAlipayArgs struct {
	Req *LoginByAlipayReq `thrift:"req,1" frugal:"1,default,LoginByAlipayReq" json:"req"`
}

func NewIDPServiceLoginByAlipayArgs() *IDPServiceLoginByAlipayArgs {
	return &IDPServiceLoginByAlipayArgs{}
}

func (p *IDPServiceLoginByAlipayArgs) InitDefault() {
}

var IDPServiceLoginByAlipayArgs_Req_DEFAULT *LoginByAlipayReq

func (p *IDPServiceLoginByAlipayArgs) GetReq() (v *LoginByAlipayReq) {
	if !p.IsSetReq() {
		return IDPServiceLoginByAlipayArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IDPServiceLoginByAlipayArgs) SetReq(val *LoginByAlipayReq) {
	p.Req = val
}

func (p *IDPServiceLoginByAlipayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IDPServiceLoginByAlipayArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceLoginByAlipayArgs(%+v)", *p)
}

var fieldIDToName_IDPServiceLoginByAlipayArgs = map[int16]string{
	1: "req",
}

type IDPServiceLoginByAlipayResult struct {
	Success *LoginByAlipayResp `thrift:"success,0,optional" frugal:"0,optional,LoginByAlipayResp" json:"success,omitempty"`
}

func NewIDPServiceLoginByAlipayResult() *IDPServiceLoginByAlipayResult {
	return &IDPServiceLoginByAlipayResult{}
}

func (p *IDPServiceLoginByAlipayResult) InitDefault() {
}

var IDPServiceLoginByAlipayResult_Success_DEFAULT *LoginByAlipayResp

func (p *IDPServiceLoginByAlipayResult) GetSuccess() (v *LoginByAlipayResp) {
	if !p.IsSetSuccess() {
		return IDPServiceLoginByAlipayResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IDPServiceLoginByAlipayResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginByAlipayResp)
}

func (p *IDPServiceLoginByAlipayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IDPServiceLoginByAlipayResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceLoginByAlipayResult(%+v)", *p)
}

var fieldIDToName_IDPServiceLoginByAlipayResult = map[int16]string{
	0: "success",
}

type IDPServiceRefreshTokenArgs struct {
	Req *RefreshTokenReq `thrift:"req,1" frugal:"1,default,RefreshTokenReq" json:"req"`
}

func NewIDPServiceRefreshTokenArgs() *IDPServiceRefreshTokenArgs {
	return &IDPServiceRefreshTokenArgs{}
}

func (p *IDPServiceRefreshTokenArgs) InitDefault() {
}

var IDPServiceRefreshTokenArgs_Req_DEFAULT *RefreshTokenReq

func (p *IDPServiceRefreshTokenArgs) GetReq() (v *RefreshTokenReq) {
	if !p.IsSetReq() {
		return IDPServiceRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IDPServiceRefreshTokenArgs) SetReq(val *RefreshTokenReq) {
	p.Req = val
}

func (p *IDPServiceRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IDPServiceRefreshTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceRefreshTokenArgs(%+v)", *p)
}

var fieldIDToName_IDPServiceRefreshTokenArgs = map[int16]string{
	1: "req",
}

type IDPServiceRefreshTokenResult struct {
	Success *RefreshTokenResp `thrift:"success,0,optional" frugal:"0,optional,RefreshTokenResp" json:"success,omitempty"`
}

func NewIDPServiceRefreshTokenResult() *IDPServiceRefreshTokenResult {
	return &IDPServiceRefreshTokenResult{}
}

func (p *IDPServiceRefreshTokenResult) InitDefault() {
}

var IDPServiceRefreshTokenResult_Success_DEFAULT *RefreshTokenResp

func (p *IDPServiceRefreshTokenResult) GetSuccess() (v *RefreshTokenResp) {
	if !p.IsSetSuccess() {
		return IDPServiceRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IDPServiceRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefreshTokenResp)
}

func (p *IDPServiceRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IDPServiceRefreshTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceRefreshTokenResult(%+v)", *p)
}

var fieldIDToName_IDPServiceRefreshTokenResult = map[int16]string{
	0: "success",
}

type IDPServiceVerifyTokenArgs struct {
	Req *VerifyTokenReq `thrift:"req,1" frugal:"1,default,VerifyTokenReq" json:"req"`
}

func NewIDPServiceVerifyTokenArgs() *IDPServiceVerifyTokenArgs {
	return &IDPServiceVerifyTokenArgs{}
}

func (p *IDPServiceVerifyTokenArgs) InitDefault() {
}

var IDPServiceVerifyTokenArgs_Req_DEFAULT *VerifyTokenReq

func (p *IDPServiceVerifyTokenArgs) GetReq() (v *VerifyTokenReq) {
	if !p.IsSetReq() {
		return IDPServiceVerifyTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *IDPServiceVerifyTokenArgs) SetReq(val *VerifyTokenReq) {
	p.Req = val
}

func (p *IDPServiceVerifyTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IDPServiceVerifyTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceVerifyTokenArgs(%+v)", *p)
}

var fieldIDToName_IDPServiceVerifyTokenArgs = map[int16]string{
	1: "req",
}

type IDPServiceVerifyTokenResult struct {
	Success *VerifyTokenResp `thrift:"success,0,optional" frugal:"0,optional,VerifyTokenResp" json:"success,omitempty"`
}

func NewIDPServiceVerifyTokenResult() *IDPServiceVerifyTokenResult {
	return &IDPServiceVerifyTokenResult{}
}

func (p *IDPServiceVerifyTokenResult) InitDefault() {
}

var IDPServiceVerifyTokenResult_Success_DEFAULT *VerifyTokenResp

func (p *IDPServiceVerifyTokenResult) GetSuccess() (v *VerifyTokenResp) {
	if !p.IsSetSuccess() {
		return IDPServiceVerifyTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IDPServiceVerifyTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifyTokenResp)
}

func (p *IDPServiceVerifyTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IDPServiceVerifyTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IDPServiceVerifyTokenResult(%+v)", *p)
}

var fieldIDToName_IDPServiceVerifyTokenResult = map[int16]string{
	0: "success",
}
