// Code generated by Kitex v0.16.1. DO NOT EDIT.

package idpservice

import (
	"context"
	idp "github.com/castlexu/micro-service/services/idp/kitex_gen/idp"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetGoogleAuthURL(ctx context.Context, req *idp.GetGoogleAuthURLReq, callOptions ...callopt.Option) (r *idp.GetGoogleAuthURLResp, err error)
	LoginByGoogle(ctx context.Context, req *idp.LoginByGoogleReq, callOptions ...callopt.Option) (r *idp.LoginByGoogleResp, err error)
	GetAlipayAuthURL(ctx context.Context, req *idp.GetAlipayAuthURLReq, callOptions ...callopt.Option) (r *idp.GetAlipayAuthURLResp, err error)
	LoginByAlipay(ctx context.Context, req *idp.LoginByAlipayReq, callOptions ...callopt.Option) (r *idp.LoginByAlipayResp, err error)
	Register(ctx context.Context, req *idp.RegisterReq, callOptions ...callopt.Option) (r *idp.RegisterResp, err error)
	LoginByPassword(ctx context.Context, req *idp.LoginByPasswordReq, callOptions ...callopt.Option) (r *idp.LoginByPasswordResp, err error)
	RefreshToken(ctx context.Context, req *idp.RefreshTokenReq, callOptions ...callopt.Option) (r *idp.RefreshTokenResp, err error)
	VerifyToken(ctx context.Context, req *idp.VerifyTokenReq, callOptions ...callopt.Option) (r *idp.VerifyTokenResp, err error)
	RevokeUserTokens(ctx context.Context, req *idp.RevokeUserTokensReq, callOptions ...callopt.Option) (r *idp.RevokeUserTokensResp, err error)
	BanUser(ctx context.Context, req *idp.BanUserReq, callOptions ...callopt.Option) (r *idp.BanUserResp, err error)
	UnbanUser(ctx context.Context, req *idp.UnbanUserReq, callOptions ...callopt.Option) (r *idp.UnbanUserResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kIDPServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kIDPServiceClient struct {
	*kClient
}

func (p *kIDPServiceClient) GetGoogleAuthURL(ctx context.Context, req *idp.GetGoogleAuthURLReq, callOptions ...callopt.Option) (r *idp.GetGoogleAuthURLResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGoogleAuthURL(ctx, req)
}

func (p *kIDPServiceClient) LoginByGoogle(ctx context.Context, req *idp.LoginByGoogleReq, callOptions ...callopt.Option) (r *idp.LoginByGoogleResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LoginByGoogle(ctx, req)
}

func (p *kIDPServiceClient) GetAlipayAuthURL(ctx context.Context, req *idp.GetAlipayAuthURLReq, callOptions ...callopt.Option) (r *idp.GetAlipayAuthURLResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAlipayAuthURL(ctx, req)
}

func (p *kIDPServiceClient) LoginByAlipay(ctx context.Context, req *idp.LoginByAlipayReq, callOptions ...callopt.Option) (r *idp.LoginByAlipayResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LoginByAlipay(ctx, req)
}

func (p *kIDPServiceClient) Register(ctx context.Context, req *idp.RegisterReq, callOptions ...callopt.Option) (r *idp.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kIDPServiceClient) LoginByPassword(ctx context.Context, req *idp.LoginByPasswordReq, callOptions ...callopt.Option) (r *idp.LoginByPasswordResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LoginByPassword(ctx, req)
}

func (p *kIDPServiceClient) RefreshToken(ctx context.Context, req *idp.RefreshTokenReq, callOptions ...callopt.Option) (r *idp.RefreshTokenResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshToken(ctx, req)
}

func (p *kIDPServiceClient) VerifyToken(ctx context.Context, req *idp.VerifyTokenReq, callOptions ...callopt.Option) (r *idp.VerifyTokenResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyToken(ctx, req)
}

func (p *kIDPServiceClient) RevokeUserTokens(ctx context.Context, req *idp.RevokeUserTokensReq, callOptions ...callopt.Option) (r *idp.RevokeUserTokensResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeUserTokens(ctx, req)
}

func (p *kIDPServiceClient) BanUser(ctx context.Context, req *idp.BanUserReq, callOptions ...callopt.Option) (r *idp.BanUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BanUser(ctx, req)
}

func (p *kIDPServiceClient) UnbanUser(ctx context.Context, req *idp.UnbanUserReq, callOptions ...callopt.Option) (r *idp.UnbanUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnbanUser(ctx, req)
}
