// Code generated by Kitex v0.16.1. DO NOT EDIT.

package idpservice

import (
	"context"
	"errors"
	idp "github.com/castlexu/micro-service/services/idp/kitex_gen/idp"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetGoogleAuthURL": kitex.NewMethodInfo(
		getGoogleAuthURLHandler,
		newIDPServiceGetGoogleAuthURLArgs,
		newIDPServiceGetGoogleAuthURLResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LoginByGoogle": kitex.NewMethodInfo(
		loginByGoogleHandler,
		newIDPServiceLoginByGoogleArgs,
		newIDPServiceLoginByGoogleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newIDPServiceRefreshTokenArgs,
		newIDPServiceRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyToken": kitex.NewMethodInfo(
		verifyTokenHandler,
		newIDPServiceVerifyTokenArgs,
		newIDPServiceVerifyTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	iDPServiceServiceInfo                = NewServiceInfo()
	iDPServiceServiceInfoForClient       = NewServiceInfoForClient()
	iDPServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return iDPServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return iDPServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return iDPServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "IDPService"
	handlerType := (*idp.IDPService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "idp",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getGoogleAuthURLHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceGetGoogleAuthURLArgs)
	realResult := result.(*idp.IDPServiceGetGoogleAuthURLResult)
	success, err := handler.(idp.IDPService).GetGoogleAuthURL(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceGetGoogleAuthURLArgs() interface{} {
	return idp.NewIDPServiceGetGoogleAuthURLArgs()
}

func newIDPServiceGetGoogleAuthURLResult() interface{} {
	return idp.NewIDPServiceGetGoogleAuthURLResult()
}

func loginByGoogleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceLoginByGoogleArgs)
	realResult := result.(*idp.IDPServiceLoginByGoogleResult)
	success, err := handler.(idp.IDPService).LoginByGoogle(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceLoginByGoogleArgs() interface{} {
	return idp.NewIDPServiceLoginByGoogleArgs()
}

func newIDPServiceLoginByGoogleResult() interface{} {
	return idp.NewIDPServiceLoginByGoogleResult()
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceRefreshTokenArgs)
	realResult := result.(*idp.IDPServiceRefreshTokenResult)
	success, err := handler.(idp.IDPService).RefreshToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceRefreshTokenArgs() interface{} {
	return idp.NewIDPServiceRefreshTokenArgs()
}

func newIDPServiceRefreshTokenResult() interface{} {
	return idp.NewIDPServiceRefreshTokenResult()
}

func verifyTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceVerifyTokenArgs)
	realResult := result.(*idp.IDPServiceVerifyTokenResult)
	success, err := handler.(idp.IDPService).VerifyToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceVerifyTokenArgs() interface{} {
	return idp.NewIDPServiceVerifyTokenArgs()
}

func newIDPServiceVerifyTokenResult() interface{} {
	return idp.NewIDPServiceVerifyTokenResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetGoogleAuthURL(ctx context.Context, req *idp.GetGoogleAuthURLReq) (r *idp.GetGoogleAuthURLResp, err error) {
	var _args idp.IDPServiceGetGoogleAuthURLArgs
	_args.Req = req
	var _result idp.IDPServiceGetGoogleAuthURLResult
	if err = p.c.Call(ctx, "GetGoogleAuthURL", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginByGoogle(ctx context.Context, req *idp.LoginByGoogleReq) (r *idp.LoginByGoogleResp, err error) {
	var _args idp.IDPServiceLoginByGoogleArgs
	_args.Req = req
	var _result idp.IDPServiceLoginByGoogleResult
	if err = p.c.Call(ctx, "LoginByGoogle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, req *idp.RefreshTokenReq) (r *idp.RefreshTokenResp, err error) {
	var _args idp.IDPServiceRefreshTokenArgs
	_args.Req = req
	var _result idp.IDPServiceRefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyToken(ctx context.Context, req *idp.VerifyTokenReq) (r *idp.VerifyTokenResp, err error) {
	var _args idp.IDPServiceVerifyTokenArgs
	_args.Req = req
	var _result idp.IDPServiceVerifyTokenResult
	if err = p.c.Call(ctx, "VerifyToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
