// Code generated by Kitex v0.16.1. DO NOT EDIT.

package idpservice

import (
	"context"
	"errors"
	idp "github.com/castlexu/micro-service/services/idp/kitex_gen/idp"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetGoogleAuthURL": kitex.NewMethodInfo(
		getGoogleAuthURLHandler,
		newIDPServiceGetGoogleAuthURLArgs,
		newIDPServiceGetGoogleAuthURLResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LoginByGoogle": kitex.NewMethodInfo(
		loginByGoogleHandler,
		newIDPServiceLoginByGoogleArgs,
		newIDPServiceLoginByGoogleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAlipayAuthURL": kitex.NewMethodInfo(
		getAlipayAuthURLHandler,
		newIDPServiceGetAlipayAuthURLArgs,
		newIDPServiceGetAlipayAuthURLResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LoginByAlipay": kitex.NewMethodInfo(
		loginByAlipayHandler,
		newIDPServiceLoginByAlipayArgs,
		newIDPServiceLoginByAlipayResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newIDPServiceRegisterArgs,
		newIDPServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LoginByPassword": kitex.NewMethodInfo(
		loginByPasswordHandler,
		newIDPServiceLoginByPasswordArgs,
		newIDPServiceLoginByPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newIDPServiceRefreshTokenArgs,
		newIDPServiceRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyToken": kitex.NewMethodInfo(
		verifyTokenHandler,
		newIDPServiceVerifyTokenArgs,
		newIDPServiceVerifyTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RevokeUserTokens": kitex.NewMethodInfo(
		revokeUserTokensHandler,
		newIDPServiceRevokeUserTokensArgs,
		newIDPServiceRevokeUserTokensResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BanUser": kitex.NewMethodInfo(
		banUserHandler,
		newIDPServiceBanUserArgs,
		newIDPServiceBanUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnbanUser": kitex.NewMethodInfo(
		unbanUserHandler,
		newIDPServiceUnbanUserArgs,
		newIDPServiceUnbanUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	iDPServiceServiceInfo                = NewServiceInfo()
	iDPServiceServiceInfoForClient       = NewServiceInfoForClient()
	iDPServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return iDPServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return iDPServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return iDPServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "IDPService"
	handlerType := (*idp.IDPService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "idp",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getGoogleAuthURLHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceGetGoogleAuthURLArgs)
	realResult := result.(*idp.IDPServiceGetGoogleAuthURLResult)
	success, err := handler.(idp.IDPService).GetGoogleAuthURL(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceGetGoogleAuthURLArgs() interface{} {
	return idp.NewIDPServiceGetGoogleAuthURLArgs()
}

func newIDPServiceGetGoogleAuthURLResult() interface{} {
	return idp.NewIDPServiceGetGoogleAuthURLResult()
}

func loginByGoogleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceLoginByGoogleArgs)
	realResult := result.(*idp.IDPServiceLoginByGoogleResult)
	success, err := handler.(idp.IDPService).LoginByGoogle(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceLoginByGoogleArgs() interface{} {
	return idp.NewIDPServiceLoginByGoogleArgs()
}

func newIDPServiceLoginByGoogleResult() interface{} {
	return idp.NewIDPServiceLoginByGoogleResult()
}

func getAlipayAuthURLHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceGetAlipayAuthURLArgs)
	realResult := result.(*idp.IDPServiceGetAlipayAuthURLResult)
	success, err := handler.(idp.IDPService).GetAlipayAuthURL(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceGetAlipayAuthURLArgs() interface{} {
	return idp.NewIDPServiceGetAlipayAuthURLArgs()
}

func newIDPServiceGetAlipayAuthURLResult() interface{} {
	return idp.NewIDPServiceGetAlipayAuthURLResult()
}

func loginByAlipayHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceLoginByAlipayArgs)
	realResult := result.(*idp.IDPServiceLoginByAlipayResult)
	success, err := handler.(idp.IDPService).LoginByAlipay(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceLoginByAlipayArgs() interface{} {
	return idp.NewIDPServiceLoginByAlipayArgs()
}

func newIDPServiceLoginByAlipayResult() interface{} {
	return idp.NewIDPServiceLoginByAlipayResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceRegisterArgs)
	realResult := result.(*idp.IDPServiceRegisterResult)
	success, err := handler.(idp.IDPService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceRegisterArgs() interface{} {
	return idp.NewIDPServiceRegisterArgs()
}

func newIDPServiceRegisterResult() interface{} {
	return idp.NewIDPServiceRegisterResult()
}

func loginByPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceLoginByPasswordArgs)
	realResult := result.(*idp.IDPServiceLoginByPasswordResult)
	success, err := handler.(idp.IDPService).LoginByPassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceLoginByPasswordArgs() interface{} {
	return idp.NewIDPServiceLoginByPasswordArgs()
}

func newIDPServiceLoginByPasswordResult() interface{} {
	return idp.NewIDPServiceLoginByPasswordResult()
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceRefreshTokenArgs)
	realResult := result.(*idp.IDPServiceRefreshTokenResult)
	success, err := handler.(idp.IDPService).RefreshToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceRefreshTokenArgs() interface{} {
	return idp.NewIDPServiceRefreshTokenArgs()
}

func newIDPServiceRefreshTokenResult() interface{} {
	return idp.NewIDPServiceRefreshTokenResult()
}

func verifyTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceVerifyTokenArgs)
	realResult := result.(*idp.IDPServiceVerifyTokenResult)
	success, err := handler.(idp.IDPService).VerifyToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceVerifyTokenArgs() interface{} {
	return idp.NewIDPServiceVerifyTokenArgs()
}

func newIDPServiceVerifyTokenResult() interface{} {
	return idp.NewIDPServiceVerifyTokenResult()
}

func revokeUserTokensHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceRevokeUserTokensArgs)
	realResult := result.(*idp.IDPServiceRevokeUserTokensResult)
	success, err := handler.(idp.IDPService).RevokeUserTokens(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceRevokeUserTokensArgs() interface{} {
	return idp.NewIDPServiceRevokeUserTokensArgs()
}

func newIDPServiceRevokeUserTokensResult() interface{} {
	return idp.NewIDPServiceRevokeUserTokensResult()
}

func banUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceBanUserArgs)
	realResult := result.(*idp.IDPServiceBanUserResult)
	success, err := handler.(idp.IDPService).BanUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceBanUserArgs() interface{} {
	return idp.NewIDPServiceBanUserArgs()
}

func newIDPServiceBanUserResult() interface{} {
	return idp.NewIDPServiceBanUserResult()
}

func unbanUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idp.IDPServiceUnbanUserArgs)
	realResult := result.(*idp.IDPServiceUnbanUserResult)
	success, err := handler.(idp.IDPService).UnbanUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIDPServiceUnbanUserArgs() interface{} {
	return idp.NewIDPServiceUnbanUserArgs()
}

func newIDPServiceUnbanUserResult() interface{} {
	return idp.NewIDPServiceUnbanUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetGoogleAuthURL(ctx context.Context, req *idp.GetGoogleAuthURLReq) (r *idp.GetGoogleAuthURLResp, err error) {
	var _args idp.IDPServiceGetGoogleAuthURLArgs
	_args.Req = req
	var _result idp.IDPServiceGetGoogleAuthURLResult
	if err = p.c.Call(ctx, "GetGoogleAuthURL", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginByGoogle(ctx context.Context, req *idp.LoginByGoogleReq) (r *idp.LoginByGoogleResp, err error) {
	var _args idp.IDPServiceLoginByGoogleArgs
	_args.Req = req
	var _result idp.IDPServiceLoginByGoogleResult
	if err = p.c.Call(ctx, "LoginByGoogle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAlipayAuthURL(ctx context.Context, req *idp.GetAlipayAuthURLReq) (r *idp.GetAlipayAuthURLResp, err error) {
	var _args idp.IDPServiceGetAlipayAuthURLArgs
	_args.Req = req
	var _result idp.IDPServiceGetAlipayAuthURLResult
	if err = p.c.Call(ctx, "GetAlipayAuthURL", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginByAlipay(ctx context.Context, req *idp.LoginByAlipayReq) (r *idp.LoginByAlipayResp, err error) {
	var _args idp.IDPServiceLoginByAlipayArgs
	_args.Req = req
	var _result idp.IDPServiceLoginByAlipayResult
	if err = p.c.Call(ctx, "LoginByAlipay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *idp.RegisterReq) (r *idp.RegisterResp, err error) {
	var _args idp.IDPServiceRegisterArgs
	_args.Req = req
	var _result idp.IDPServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginByPassword(ctx context.Context, req *idp.LoginByPasswordReq) (r *idp.LoginByPasswordResp, err error) {
	var _args idp.IDPServiceLoginByPasswordArgs
	_args.Req = req
	var _result idp.IDPServiceLoginByPasswordResult
	if err = p.c.Call(ctx, "LoginByPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, req *idp.RefreshTokenReq) (r *idp.RefreshTokenResp, err error) {
	var _args idp.IDPServiceRefreshTokenArgs
	_args.Req = req
	var _result idp.IDPServiceRefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyToken(ctx context.Context, req *idp.VerifyTokenReq) (r *idp.VerifyTokenResp, err error) {
	var _args idp.IDPServiceVerifyTokenArgs
	_args.Req = req
	var _result idp.IDPServiceVerifyTokenResult
	if err = p.c.Call(ctx, "VerifyToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RevokeUserTokens(ctx context.Context, req *idp.RevokeUserTokensReq) (r *idp.RevokeUserTokensResp, err error) {
	var _args idp.IDPServiceRevokeUserTokensArgs
	_args.Req = req
	var _result idp.IDPServiceRevokeUserTokensResult
	if err = p.c.Call(ctx, "RevokeUserTokens", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BanUser(ctx context.Context, req *idp.BanUserReq) (r *idp.BanUserResp, err error) {
	var _args idp.IDPServiceBanUserArgs
	_args.Req = req
	var _result idp.IDPServiceBanUserResult
	if err = p.c.Call(ctx, "BanUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnbanUser(ctx context.Context, req *idp.UnbanUserReq) (r *idp.UnbanUserResp, err error) {
	var _args idp.IDPServiceUnbanUserArgs
	_args.Req = req
	var _result idp.IDPServiceUnbanUserResult
	if err = p.c.Call(ctx, "UnbanUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
